// Auto-generated from WooCommerce CSV — Italia Cosmetics Pakistan
// 276 products across MAXY LOOK, UNA, VERSUM 2.0, GENUS brands
// All prices in PKR (Pakistani Rupees)

export type ProductCategory =
  | "shampoos"
  | "conditioners-masks"
  | "styling-finishing"
  | "technical-coloring"
  | "treatments-serums"
  | "other";

export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number; // PKR
  category: ProductCategory;
  image: string;
  rating: number;
  description: string;
  italianName?: string;
  size?: string;
  ingredients?: string;
  usage?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "max801",
    name: "1 BLACK - NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max801-black.svg",
    rating: 4.6,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max898",
    name: "1.10 BLUE BLACK - ASH NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max898-blue-black.svg",
    rating: 4.6,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max802",
    name: "3 DARK BROWN - NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max802-dark-brown.svg",
    rating: 4.6,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max803",
    name: "4 BROWN - NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max803-brown.svg",
    rating: 4.3,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max804",
    name: "5 LIGHT BROWN - NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max804-light-brown.svg",
    rating: 4.4,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max805",
    name: "6 DARK BLONDE - NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max805-dark-blonde.svg",
    rating: 4.4,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max806",
    name: "7 BLONDE - NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max806-blonde.svg",
    rating: 4.4,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max807",
    name: "8 LIGHT BLONDE - NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max807-light-blonde.svg",
    rating: 4.5,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max808",
    name: "9 VERY LIGHT BLONDE - NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max808-very-light-blonde.svg",
    rating: 4.5,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max809",
    name: "10 PLATINUM BLONDE - NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max809-platinum-blonde.svg",
    rating: 4.5,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max810",
    name: "5.00 INTENSE LIGHT NATURAL BROWN - INTENSIVE NATURALS PERMANENT COLORING CREAM 100 ML",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "/images/swatches/max810-intense-light-natural-brown.svg",
    rating: 4.6,
    description: "With Passion Flower. The special formulation ensures maximum coverage of white hair and intense reflections for a vivid, brilliant, and long-lasting color. 99 shades for infinite color combinations.",
    size: "100 ml",
  },
  {
    id: "max916",
    name: "DIRECT COLORING ETHEREAL WHITE 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max916-ethereal-white.svg",
    rating: 4.5,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max917",
    name: "DIRECT COLORING BLUE 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max917-blue.svg",
    rating: 4.5,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max918",
    name: "DIRECT COLORING GREEN 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max918-green.svg",
    rating: 4.6,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max919",
    name: "DIRECT COLORING ACID GREEN 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max919-acid-green.svg",
    rating: 4.6,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max920",
    name: "DIRECT COLORING PINK 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max920-pink.svg",
    rating: 4.3,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max921",
    name: "DIRECT COLORING PLUM 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max921-plum.svg",
    rating: 4.4,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max922",
    name: "DIRECT COLORING TURQUOISE 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max922-turquoise.svg",
    rating: 4.4,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max923",
    name: "DIRECT COLORING ORANGE 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max923-orange.svg",
    rating: 4.4,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max924",
    name: "DIRECT COLORING YELLOW 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max924-yellow.svg",
    rating: 4.5,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max925",
    name: "DIRECT COLORING RED 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max925-red.svg",
    rating: 4.5,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max926",
    name: "DIRECT COLORING PEARL GREY 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max926-pearl-grey.svg",
    rating: 4.5,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max927",
    name: "DIRECT COLORING CLEAR 60 ML",
    brand: "MAXY LOOK",
    price: 7107,
    category: "technical-coloring",
    image: "/images/swatches/max927-clear.svg",
    rating: 4.6,
    description: "Direct cream coloring, without peroxide and without ammonia, ideal for giving new reflections to natural, colored or bleached hair. The 12 shades are ready to use and can be mixed together for surprising results.",
    size: "60 ml",
  },
  {
    id: "max601",
    name: "PROTECTING SHAMPOO 1000 ML",
    brand: "MAXY LOOK",
    price: 13688,
    category: "shampoos",
    image: "/images/swatches/max601-protecting-shampoo.svg",
    rating: 4.5,
    description: "Protective shampoo for colored and chemically treated hair. Enriched with Collagen, Blueberry, Aloe and Hyaluronic Acid, it gently cleanses and protects the color intensity, enhancing reflections and brightness. Use: apply to wet hair, massage thoroughly and rinse.",
    size: "1000 ml",
  },
  {
    id: "max602",
    name: "PROTECTING SHAMPOO 300 ML",
    brand: "MAXY LOOK",
    price: 7036,
    category: "shampoos",
    image: "/images/swatches/max602-protecting-shampoo-300ml.svg",
    rating: 4.6,
    description: "Protective shampoo for colored and chemically treated hair. Enriched with Collagen, Blueberry, Aloe and Hyaluronic Acid, it gently cleanses and protects the color intensity, enhancing reflections and brightness. Use: apply to wet hair, massage thoroughly and rinse.",
    size: "300 ml",
  },
  {
    id: "max603",
    name: "Protecting Mask 1000 ML",
    italianName: "Maschera protettiva per capelli colorati",
    brand: "MAXY LOOK",
    price: 13859,
    category: "conditioners-masks",
    image: "/images/swatches/MAX603-protecting-mask-1000-ml.svg",
    rating: 4.8,
    description: "Protective mask for colored and chemically treated hair. The formula with Collagen, Blueberry, Aloe, and Hyaluronic Acid moisturizes and exerts an antioxidant action that protects the intensity of the color and enhances reflections, leaving hair bright, elastic, and silky.",
    usage: "After shampooing, apply to lengths and ends, leave on for 5 minutes, and rinse.",
    ingredients: "Collagen, Blueberry, Aloe, Hyaluronic Acid",
    size: "1000 ml",
  },
  {
    id: "max604",
    name: "Protecting Mask 300 ML",
    italianName: "Maschera protettiva per capelli colorati",
    brand: "MAXY LOOK",
    price: 7932,
    category: "conditioners-masks",
    image: "/images/swatches/MAX604-protecting-mask-300-ml.svg",
    rating: 4.8,
    description: "Protective mask for colored and chemically treated hair. The formula with Collagen, Blueberry, Aloe, and Hyaluronic Acid moisturizes and exerts an antioxidant action that protects the intensity of the color and enhances reflections, leaving hair bright, elastic, and silky.",
    usage: "After shampooing, apply to lengths and ends, leave on for 5 minutes, and rinse.",
    ingredients: "Collagen, Blueberry, Aloe, Hyaluronic Acid",
    size: "300 ml",
  },
  {
    id: "max605",
    name: "Protecting Dual-Phase Spray 300 ML",
    italianName: "Spray bifasico protettivo",
    brand: "MAXY LOOK",
    price: 8813,
    category: "styling-finishing",
    image: "/images/swatches/MAX605-Protecting-Dual-phase-Spray-300ml.svg",
    rating: 4.6,
    description: "Leave-in dual-phase spray for chemically treated hair. The formula enriched with Collagen, Blueberry extract, Hyaluronic Acid, and Aloe vera hydrates and restores the correct PH of the hair, making it shiny and easy to comb, without weighing it down.",
    usage: "Shake well before use. Spray on washed and towel-dried hair and proceed with drying.",
    ingredients: "Collagen, Blueberry extract, Aloe vera, Hyaluronic Acid",
    size: "300 ml",
  },
  {
    id: "max606",
    name: "Nourishing Shampoo 1000 ML",
    italianName: "Shampoo nutriente",
    brand: "MAXY LOOK",
    price: 13688,
    category: "shampoos",
    image: "/images/swatches/MAX606-Nourishing-Shampoo-1000-ml.svg",
    rating: 4.8,
    description: "Nourishing shampoo for damaged, frizzy, and chemically treated hair. Enriched with Hydrolyzed Quinoa Proteins, Keratin, and Shea Butter, it gently cleanses providing nourishment and hydration. It gives hair softness and combability.",
    usage: "Apply to wet hair, massage, and rinse.",
    ingredients: "Hydrolyzed Quinoa Proteins, Keratin, Shea Butter",
    size: "1000 ml",
  },
  {
    id: "max607",
    name: "Nourishing Shampoo 300 ML",
    italianName: "Shampoo nutriente",
    brand: "MAXY LOOK",
    price: 7036,
    category: "shampoos",
    image: "/images/swatches/MAX607-Nourishing-Shampoo-300-ml.svg",
    rating: 4.7,
    description: "Nourishing shampoo for damaged, frizzy, and chemically treated hair. Enriched with Hydrolyzed Quinoa Proteins, Keratin, and Shea Butter, it gently cleanses providing nourishment and hydration. It gives hair softness and combability.",
    usage: "Apply to wet hair, massage, and rinse.",
    ingredients: "Hydrolyzed Quinoa Proteins, Keratin, Shea Butter",
    size: "300 ml",
  },
  {
    id: "max608",
    name: "Nourishing Mask 1000 ML",
    italianName: "Maschera nutriente",
    brand: "MAXY LOOK",
    price: 13859,
    category: "conditioners-masks",
    image: "/images/swatches/MAX608-Nourishing-Mask-1000-ml.svg",
    rating: 4.8,
    description: "Nourishing mask for damaged, frizzy, and chemically treated hair. The formula with Hydrolyzed Quinoa Proteins, Keratin, and Shea Butter nourishes, repairs, and strengthens the hair structure, providing extraordinary softness and combability.",
    usage: "After shampooing, apply to lengths and ends, leave on for 5 minutes, and rinse.",
    ingredients: "Hydrolyzed Quinoa Proteins, Keratin, Shea Butter",
    size: "1000 ml",
  },
  {
    id: "max609",
    name: "Nourishing Mask 300 ML",
    italianName: "Maschera nutriente",
    brand: "MAXY LOOK",
    price: 7932,
    category: "conditioners-masks",
    image: "/images/swatches/MAX609-Nourishing-Mask-300-ml.svg",
    rating: 4.6,
    description: "Nourishing mask for damaged, frizzy, and chemically treated hair. The formula with Hydrolyzed Quinoa Proteins, Keratin, and Shea Butter nourishes, repairs, and strengthens the hair structure, providing extraordinary softness and combability.",
    usage: "After shampooing, apply to lengths and ends, leave on for 5 minutes, and rinse.",
    ingredients: "Hydrolyzed Quinoa Proteins, Keratin, Shea Butter",
    size: "300 ml",
  },
  {
    id: "max610",
    name: "Nourishing Conditioner Leave-in 300 ML",
    italianName: "Conditioner senza risciacquo",
    brand: "MAXY LOOK",
    price: 11556,
    category: "conditioners-masks",
    image: "/images/swatches/MAX610-Nourishing-Conditioner-Leave-in.svg",
    rating: 4.8,
    description: "Leave-in conditioner for damaged, frizzy, and chemically treated hair. Enriched with a rich protein blend composed of Keratin and Quinoa, it repairs and strengthens the hair structure, while deep hydrating thanks to Shea Butter. The hair will be soft, silky, and easy to comb.",
    usage: "Apply evenly to washed and towel-dried hair only on lengths and ends. Comb and proceed with drying.",
    ingredients: "Keratin, Quinoa, Shea Butter",
    size: "300 ml",
  },
  {
    id: "max612",
    name: "Hydrating Shampoo 1000 ML",
    italianName: "Shampoo idratante",
    brand: "MAXY LOOK",
    price: 13688,
    category: "shampoos",
    image: "/images/swatches/MAX612-Hydrating-Shampoo-1000-ml.svg",
    rating: 4.8,
    description: "Hydrating shampoo for dry and dull hair. Enriched with Macadamia, Prickly Pear, and Almond oil, it gently cleanses and deeply hydrates, giving hair vitality and lightness.",
    usage: "Apply to wet hair, massage, and rinse.",
    ingredients: "Macadamia, Prickly Pear oil, Almond oil",
    size: "1000 ml",
  },
  {
    id: "max613",
    name: "Hydrating Shampoo 300 ML",
    italianName: "Shampoo idratante",
    brand: "MAXY LOOK",
    price: 7036,
    category: "shampoos",
    image: "/images/swatches/MAX613-Hydrating-Shampoo-300-ml.svg",
    rating: 4.6,
    description: "Hydrating shampoo for dry and dull hair. Enriched with Macadamia, Prickly Pear, and Almond oil, it gently cleanses and deeply hydrates, giving hair vitality and lightness.",
    usage: "Apply to wet hair, massage, and rinse.",
    ingredients: "Macadamia, Prickly Pear oil, Almond oil",
    size: "300 ml",
  },
  {
    id: "max614",
    name: "Hydrating Mask 1000 ML",
    italianName: "Maschera idratante",
    brand: "MAXY LOOK",
    price: 13859,
    category: "conditioners-masks",
    image: "/images/swatches/MAX614-Hydrating-Mask-1000-ml.svg",
    rating: 4.8,
    description: "Hydrating mask for dry and dull hair. The formula with Macadamia, Prickly Pear, and Almond oil performs an intense hydrating action that makes hair extremely soft, easy to comb, and bright, without weighing it down.",
    usage: "After shampooing, apply to lengths and ends, leave on for 5 minutes, and rinse.",
    ingredients: "Macadamia, Prickly Pear oil, Almond oil",
    size: "1000 ml",
  },
  {
    id: "max615",
    name: "Hydrating Mask 300 ML",
    italianName: "Maschera idratante",
    brand: "MAXY LOOK",
    price: 7932,
    category: "conditioners-masks",
    image: "/images/swatches/MAX615-Hydrating-Mask-300-ml.svg",
    rating: 4.6,
    description: "Hydrating mask for dry and dull hair. The formula with Macadamia, Prickly Pear, and Almond oil performs an intense hydrating action that makes hair extremely soft, easy to comb, and bright, without weighing it down.",
    usage: "After shampooing, apply to lengths and ends, leave on for 5 minutes, and rinse.",
    ingredients: "Macadamia, Prickly Pear oil, Almond oil",
    size: "300 ml",
  },
  {
    id: "max616",
    name: "Multi Action 10 in 1 Leave-in 200 ML",
    italianName: "Spray multi azione senza risciacquo",
    brand: "MAXY LOOK",
    price: 11556,
    category: "styling-finishing",
    image: "/images/swatches/MAX616-Multi-Action-10-in-1-Leave-in-200-ml.svg",
    rating: 4.8,
    description: "Multi-action leave-in spray for dry and dull hair. Its formula deeply nourishes, detangles without weighing down, envelops the hair making it silky and protecting it from heat and UV rays. It repairs split ends, adds volume, has an anti-frizz function, facilitates straightening, and illuminates the hair.",
    usage: "Spray on washed and towel-dried hair and proceed with drying.",
    ingredients: "Heat & UV protectants, Anti-frizz agents",
    size: "200 ml",
  },
  {
    id: "max617",
    name: "Hydrating Crystal Fluid 100 ML",
    italianName: "Hydrating Crystal Macadamia Fluid",
    brand: "MAXY LOOK",
    price: 17697,
    category: "styling-finishing",
    image: "/images/swatches/MAX616-HYDRATING-CRYSTAL-100-ML.svg",
    rating: 4.8,
    description: "Hydrating leave-in serum for dry and dull hair. The precious blend of Macadamia and Argan oil deeply hydrates and nourishes, repairs split ends, eliminates frizz by sealing the cuticles, and transforms the hair making it immediately brighter, softer, and silkier without weighing it down.",
    usage: "Apply to damp hair, comb, then proceed with drying.",
    ingredients: "Macadamia oil, Argan oil",
    size: "100 ml",
  },
  {
    id: "max618",
    name: "Hydrating Treatment Lotion 12 X 7 ML",
    italianName: "Trattamento idratante senza risciacquo",
    brand: "MAXY LOOK",
    price: 30134,
    category: "treatments-serums",
    image: "/images/swatches/MAX618-HYDRATING-TREATMENT-12-X-7-ML.svg",
    rating: 4.8,
    description: "Hydrating leave-in treatment for dry and dull hair. The intense hydrating and nourishing action of Macadamia oil gives hair extreme softness along with a healthy and vital appearance.",
    usage: "After washing, distribute over lengths, massage, and proceed with drying.",
    ingredients: "Macadamia oil",
    size: "12 x 7 ml",
  },
  {
    id: "max625",
    name: "HYDRATING TREATMENT 100ML",
    brand: "MAXY LOOK",
    price: 17697,
    category: "treatments-serums",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX625-hydrating-treatment-lotion-100ml.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: HYDRATING TREATMENT 100ML",
  },
  {
    id: "max619",
    name: "REVITALIZING SHAMPOO 1000ML",
    brand: "MAXY LOOK",
    price: 14143,
    category: "shampoos",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX619-revitalizing-shampoo-1000-ml.png",
    rating: 4.5,
    description: "Professional Italian Hair Care: REVITALIZING SHAMPOO 1000ML",
  },
  {
    id: "max620",
    name: "REVITALIZING SHAMPOO 300ML",
    brand: "MAXY LOOK",
    price: 7462,
    category: "shampoos",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX620-revitalizing-shampoo-300-ml.png",
    rating: 4.6,
    description: "Professional Italian Hair Care: REVITALIZING SHAMPOO 300ML",
  },
  {
    id: "max621",
    name: "REVITALIZING MASK 300ML",
    brand: "MAXY LOOK",
    price: 8813,
    category: "conditioners-masks",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX621-revitalizing-mask-300-ml.png",
    rating: 4.6,
    description: "Professional Italian Hair Care: REVITALIZING MASK 300ML",
  },
  {
    id: "max622",
    name: "REVITALIZING MASK 1000ML",
    brand: "MAXY LOOK",
    price: 17412,
    category: "conditioners-masks",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX622-revitalizing-mask-1000-ml.png",
    rating: 4.3,
    description: "Professional Italian Hair Care: REVITALIZING MASK 1000ML",
  },
  {
    id: "max623",
    name: "REVITALIZING TREATMENT 12 X 7ML",
    brand: "MAXY LOOK",
    price: 30134,
    category: "treatments-serums",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX623-revitalizing-treatment-lotion-7ml-x-12.png",
    rating: 4.3,
    description: "Professional Italian Hair Care: REVITALIZING TREATMENT 12 X 7ML",
  },
  {
    id: "max624",
    name: "REVITALIZING TREATMENT 100ML",
    brand: "MAXY LOOK",
    price: 24804,
    category: "treatments-serums",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX624-revitalizing-treatment-lotion-100ml.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: REVITALIZING TREATMENT 100ML",
  },
  {
    id: "max630",
    name: "VIOLET PIGMENT NO YELLOW SHAMPOO 1000ML",
    brand: "MAXY LOOK",
    price: 14854,
    category: "shampoos",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX630-no-yellow-shampoo-1000ml.png",
    rating: 4.6,
    description: "Professional Italian Hair Care: VIOLET PIGMENT NO YELLOW SHAMPOO 1000ML",
  },
  {
    id: "max631",
    name: "VIOLET PIGMENT NO YELLOW SHAMPOO 300ML",
    brand: "MAXY LOOK",
    price: 7932,
    category: "shampoos",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX631-no-yellow-shampoo-300ml.png",
    rating: 4.3,
    description: "Professional Italian Hair Care: VIOLET PIGMENT NO YELLOW SHAMPOO 300ML",
  },
  {
    id: "max633",
    name: "VIOLET PIGMENT NO YELLOW MASK 300ML",
    brand: "MAXY LOOK",
    price: 11300,
    category: "conditioners-masks",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX633-no-yellow-mask-300ml.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: VIOLET PIGMENT NO YELLOW MASK 300ML",
  },
  {
    id: "max650",
    name: "MAXY STYLE EXTREME HAIR SPRAY 300ML",
    brand: "MAXY LOOK",
    price: 13262,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX650-extreme-hair-spray-300-ml.png",
    rating: 4.3,
    description: "Professional Italian Hair Care: MAXY STYLE EXTREME HAIR SPRAY 300ML",
  },
  {
    id: "max651",
    name: "MAXY STYLE EXTREME HAIR MOUSSE 250ML",
    brand: "MAXY LOOK",
    price: 15039,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX651-extreme-mousse-250-ml.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: MAXY STYLE EXTREME HAIR MOUSSE 250ML",
  },
  {
    id: "max652",
    name: "MAXY STYLE EXTREME GLOSSY SPRAY 115ML",
    brand: "MAXY LOOK",
    price: 17697,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX652-extreme-glossy-spray-115-ml.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: MAXY STYLE EXTREME GLOSSY SPRAY 115ML",
  },
  {
    id: "max653",
    name: "MAXY STYLE HEAT PROTECTOR SPRAY 150ML",
    brand: "MAXY LOOK",
    price: 15039,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX653-heat-protector-spray-150-ml.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: MAXY STYLE HEAT PROTECTOR SPRAY 150ML",
  },
  {
    id: "max654",
    name: "MAXY STYLE EXTREME LISS CREAM 100ML",
    brand: "MAXY LOOK",
    price: 15039,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX654-extreme-liss-cream-100-ml.png",
    rating: 4.5,
    description: "Professional Italian Hair Care: MAXY STYLE EXTREME LISS CREAM 100ML",
  },
  {
    id: "max655",
    name: "MAXY STYLE CURL CONTROL CREAM 100ML",
    brand: "MAXY LOOK",
    price: 15039,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX655-curl-control-cream-100-ml.png",
    rating: 4.5,
    description: "Professional Italian Hair Care: MAXY STYLE CURL CONTROL CREAM 100ML",
  },
  {
    id: "max825",
    name: "HARMONIC COLOR WARM NATURAL 3",
    brand: "MAXY LOOK",
    price: 6752,
    category: "technical-coloring",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX825-n7003-biondo-naturale-caldo-100-ml.png",
    rating: 4.5,
    description: "Professional Italian Hair Care: HARMONIC COLOR WARM NATURAL 3",
  },
  {
    id: "max719",
    name: "Deep Restructuring A+B Lotion",
    brand: "MAXY LOOK",
    price: 42259,
    category: "treatments-serums",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX719-ab-intense-restructuring-lotion.png",
    rating: 4.5,
    description: "Professional Italian Hair Care: LOZIONE A+B RESTRUCT. INT UOVO",
  },
  {
    id: "max720",
    name: "Restructuring and Nourishing Cream to Milk Formula 125ml",
    brand: "MAXY LOOK",
    price: 21947,
    category: "other",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX720-Restructuring-and-Nourishing-Cream-to-Milk-Formula-125ml.png",
    rating: 4.6,
    description: "Professional Italian Hair Care: CREMA RESTRUCT. UOVO 125 ML(LEAVE IN)",
  },
  {
    id: "max721",
    name: "Restructuring and Nourishing Shampoo 250 ml",
    brand: "MAXY LOOK",
    price: 12082,
    category: "shampoos",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX721-restructuring-nourishing-shampoo-250-ml.png",
    rating: 4.3,
    description: "Professional Italian Hair Care: SHAMPOO RESTRUCT. UOVO 250 ML",
  },
  {
    id: "max722",
    name: "Restructuring and Nourishing Shampoo 1000 ml",
    brand: "MAXY LOOK",
    price: 23667,
    category: "shampoos",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX721-restructuring-nourishing-shampoo-1000-ml.png",
    rating: 4.3,
    description: "Professional Italian Hair Care: SHAMPOO RESTRUCT. UOVO 1000 ML",
  },
  {
    id: "max723",
    name: "Restructuring and Nourishing Mask 350 ml",
    brand: "MAXY LOOK",
    price: 24875,
    category: "other",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX723-restructuring-nourishing-mask-350-ml.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: MACSCHERA RISTRUCT. UOVO 350 ML",
  },
  {
    id: "max725",
    name: "Deep Restructuring Kit",
    brand: "MAXY LOOK",
    price: 81035,
    category: "other",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX725-proteins-and-minerals-off-egg-kit.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: KIT MAXI LOOK EGG BOX",
  },
  {
    id: "max733",
    name: "Shampoo Moisture Repair 500 ml",
    brand: "MAXY LOOK",
    price: 20753,
    category: "shampoos",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX733-shampoo-moisture-repair-500-ml.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: ARGANWAY MOISTURE REPAIR SHAMPOO 500 ML",
  },
  {
    id: "max734",
    name: "intense-hydrating-mask-500-ml",
    brand: "MAXY LOOK",
    price: 23141,
    category: "conditioners-masks",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX734-intense-hydrating-mask-500-ml.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: ARGANWAY IINT HYDRATOR MASK 500 ML",
  },
  {
    id: "max735",
    name: "Instant Repair Leave-in Oil 100 ml",
    brand: "MAXY LOOK",
    price: 30873,
    category: "other",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX735-instant-repair-leave-in-oil-100-ml.png",
    rating: 4.5,
    description: "Professional Italian Hair Care: ARGANWAY INSTANT REPAIR LEAVE",
  },
  {
    id: "max736",
    name: "Protective Shining Spray 125 ml",
    brand: "MAXY LOOK",
    price: 32266,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX736-protective-shining-spray-125-ml.png",
    rating: 4.5,
    description: "Professional Italian Hair Care: ARGANWAYPROTECTIVE SHINNING SPRAY 125 ML",
  },
  {
    id: "max798",
    name: "Compact Bleaching Powder Blue 500 gr",
    brand: "MAXY LOOK",
    price: 22103,
    category: "technical-coloring",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX798-compact-bleaching-powder-blue-500-gr.png",
    rating: 4.4,
    description: "Professional Italian Hair Care: BLEACHING BLU DECOLORANTE 500 ML.",
  },
  {
    id: "max703",
    name: "Perfumed Oxidizing Emulsion Cream 40 vol",
    brand: "MAXY LOOK",
    price: 7932,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX703-perfumed-oxidizing-emulsion-cream-40-vol.png",
    rating: 4.3,
    description: "Professional Italian Hair Care: ML OXY IN CREAM 40 VOL",
  },
  {
    id: "max700",
    name: "Perfumed Oxidizing Emulsion Cream 10 vol",
    brand: "MAXY LOOK",
    price: 7932,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX700-perfumed-oxidizing-emulsion-cream.png",
    rating: 4.5,
    description: "Professional Italian Hair Care: ML OXY IN CREAM 10 VOL",
  },
  {
    id: "max701",
    name: "Perfumed Oxidizing Emulsion Cream 20 vol",
    brand: "MAXY LOOK",
    price: 7932,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX701-perfumed-oxidizing-emulsion-cream-20-vol.png",
    rating: 4.6,
    description: "Professional Italian Hair Care: ML OXY IN CREAM 20 VOL",
  },
  {
    id: "max702",
    name: "Perfumed Oxidizing Emulsion Cream 30 volumi",
    brand: "MAXY LOOK",
    price: 7932,
    category: "styling-finishing",
    image: "https://italiacosmetics.com/wp-content/uploads/2026/04/MAX702-perfumed-oxidizing-emulsion-cream-30-vol.png",
    rating: 4.6,
    description: "Professional Italian Hair Care: ML OXY IN CREAM 30 VOL",
  },
  {
    id: "una0061-02",
    name: "UNA ENERGIZING CHAMPU 1000ML",
    brand: "UNA",
    price: 18905,
    category: "shampoos",
    image: "/images/products/una0061-02.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA ENERGIZING CHAMPU 1000ML",
  },
  {
    id: "una0241-01",
    name: "UNA REVITALIZING HAIR ACONDICIONADOR 1000ML",
    brand: "UNA",
    price: 25728,
    category: "conditioners-masks",
    image: "/images/products/una0241-01.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA REVITALIZING HAIR ACONDICIONADOR 1000ML",
  },
  {
    id: "una0281-01",
    name: "UNA INTENSIVE PROTEIN HAIR TRATAMIENTO 250ML",
    brand: "UNA",
    price: 15565,
    category: "treatments-serums",
    image: "/images/products/una0281-01.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: UNA INTENSIVE PROTEIN HAIR TRATAMIENTO 250ML",
  },
  {
    id: "una0282-01",
    name: "UNA INTENSIVE PROTEIN HAIR TRATAMIENTO 500ML",
    brand: "UNA",
    price: 22530,
    category: "treatments-serums",
    image: "/images/products/una0282-01.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: UNA INTENSIVE PROTEIN HAIR TRATAMIENTO 500ML",
  },
  {
    id: "unar487-03",
    name: "UNA INTENSIVE PROTEIN HAIR TRATAMIENTO 1000ML",
    brand: "UNA",
    price: 29395,
    category: "treatments-serums",
    image: "/images/products/unar487-03.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA INTENSIVE PROTEIN HAIR TRATAMIENTO 1000ML",
  },
  {
    id: "una0312",
    name: "UNA RESTRUCTURIZING HAIR TRATAMIENTO 90ML GOTERO",
    brand: "UNA",
    price: 17171,
    category: "treatments-serums",
    image: "/images/products/una0312.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA RESTRUCTURIZING HAIR TRATAMIENTO 90ML GOTERO",
  },
  {
    id: "una0081-02",
    name: "UNA HYDRATING CHAMPU 1000ML",
    brand: "UNA",
    price: 18905,
    category: "shampoos",
    image: "/images/products/una0081-02.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: UNA HYDRATING CHAMPU 1000ML",
  },
  {
    id: "una0271-01",
    name: "UNA MOISTURIZING HAIR MASCARILLA 500ML",
    brand: "UNA",
    price: 18905,
    category: "conditioners-masks",
    image: "/images/products/una0271-01.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: UNA MOISTURIZING HAIR MASCARILLA 500ML",
  },
  {
    id: "unam487-03",
    name: "UNA MOISTURIZING HAIR MASCARILLA 1000ML",
    brand: "UNA",
    price: 29395,
    category: "conditioners-masks",
    image: "/images/products/unam487-03.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: UNA MOISTURIZING HAIR MASCARILLA 1000ML",
  },
  {
    id: "una0251-01",
    name: "UNA DETANGLER 250ML",
    brand: "UNA",
    price: 16744,
    category: "conditioners-masks",
    image: "/images/products/una0251-01.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA DETANGLER 250ML",
  },
  {
    id: "una0191",
    name: "UNA DAILY HYDRO-ACTIVE HAIR ACONDICIONADOR 1000ML",
    brand: "UNA",
    price: 20582,
    category: "conditioners-masks",
    image: "/images/products/una0191.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA DAILY HYDRO-ACTIVE HAIR ACONDICIONADOR 1000ML",
  },
  {
    id: "una0111-02",
    name: "UNA COMPENSATING CHAMPU 250M",
    brand: "UNA",
    price: 14186,
    category: "shampoos",
    image: "/images/products/una0111-02.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA COMPENSATING CHAMPU 250M",
  },
  {
    id: "una0121-02",
    name: "UNA COMPENSATING CHAMPU 1000ML",
    brand: "UNA",
    price: 25770,
    category: "shampoos",
    image: "/images/products/una0121-02.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA COMPENSATING CHAMPU 1000ML",
  },
  {
    id: "una0331",
    name: "UNA OXYGENATING SCALP TRATAMIENTO 12X10ML AMPOLLA",
    brand: "UNA",
    price: 36388,
    category: "treatments-serums",
    image: "/images/products/una0331.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA OXYGENATING SCALP TRATAMIENTO 12X10ML AMPOLLA",
  },
  {
    id: "una0332",
    name: "UNA OXYGENATING SCALP TRATAMIENTO 90ML GOTERO",
    brand: "UNA",
    price: 12906,
    category: "treatments-serums",
    image: "/images/products/una0332.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA OXYGENATING SCALP TRATAMIENTO 90ML GOTERO",
  },
  {
    id: "una0141-02",
    name: "UNA PURIFYING CHAMPU1000ML",
    brand: "UNA",
    price: 23098,
    category: "shampoos",
    image: "/images/products/una0141-02.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA PURIFYING CHAMPU1000ML",
  },
  {
    id: "una0041-01",
    name: "UNA NEUTRALIZING CHAMPU 1000ML",
    brand: "UNA",
    price: 19331,
    category: "shampoos",
    image: "/images/products/una0041-01.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA NEUTRALIZING CHAMPU 1000ML",
  },
  {
    id: "una0211-01",
    name: "UNA ACID HAIR ACONDICIONADOR 1000ML",
    brand: "UNA",
    price: 25728,
    category: "conditioners-masks",
    image: "/images/products/una0211-01.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA ACID HAIR ACONDICIONADOR 1000ML",
  },
  {
    id: "una0221",
    name: "UNA VITAMIN LEAVE-IN HAIR TRATAMIENTO 250ML",
    brand: "UNA",
    price: 19161,
    category: "treatments-serums",
    image: "/images/products/una0221.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: UNA VITAMIN LEAVE-IN HAIR TRATAMIENTO 250ML",
  },
  {
    id: "una0015",
    name: "UNA COCONUT OIL HAIR MASCARILLA 1000ML",
    brand: "UNA",
    price: 19232,
    category: "conditioners-masks",
    image: "/images/products/una0015.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA COCONUT OIL HAIR MASCARILLA 1000ML",
  },
  {
    id: "una0016-01",
    name: "UNA VITAMINS HAIR MASCARILLA 1000ML",
    brand: "UNA",
    price: 19232,
    category: "conditioners-masks",
    image: "/images/products/una0016-01.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA VITAMINS HAIR MASCARILLA 1000ML",
  },
  {
    id: "unam487-402",
    name: "UNA RE-BUILD THERAPY MASCARILLA 500ML",
    brand: "UNA",
    price: 19800,
    category: "conditioners-masks",
    image: "/images/products/unam487-402.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: UNA RE-BUILD THERAPY MASCARILLA 500ML",
  },
  {
    id: "unam487-1001",
    name: "UNA RE-BUILD THERAPY MASCARILLA 1000ML",
    brand: "UNA",
    price: 26197,
    category: "conditioners-masks",
    image: "/images/products/unam487-1001.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA RE-BUILD THERAPY MASCARILLA 1000ML",
  },
  {
    id: "una0421",
    name: "UNA DESIGNING OIL NON OIL 250ML",
    brand: "UNA",
    price: 16176,
    category: "treatments-serums",
    image: "/images/products/una0421.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA DESIGNING OIL NON OIL 250ML",
  },
  {
    id: "una0541",
    name: "UNA SILKER 150ML",
    brand: "UNA",
    price: 28997,
    category: "other",
    image: "/images/products/una0541.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA SILKER 150ML",
  },
  {
    id: "una0561",
    name: "UNA PURE GLOSS ABRILLANTADOR 150M",
    brand: "UNA",
    price: 27405,
    category: "styling-finishing",
    image: "/images/products/una0561.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: UNA PURE GLOSS ABRILLANTADOR 150M",
  },
  {
    id: "una0521",
    name: "UNA SCULPTING GEL 250ML",
    brand: "UNA",
    price: 10917,
    category: "styling-finishing",
    image: "/images/products/una0521.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: UNA SCULPTING GEL 250ML",
  },
  {
    id: "una0531-01",
    name: "UNA SCULPTING GEL 500ML",
    brand: "UNA",
    price: 19161,
    category: "styling-finishing",
    image: "/images/products/una0531-01.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: UNA SCULPTING GEL 500ML",
  },
  {
    id: "vs16011",
    name: "SOFTENING SHAMPOO 1000 ML",
    brand: "VERSUM 2.0",
    price: 24306,
    category: "shampoos",
    image: "/images/products/vs16011.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: SOFTENING SHAMPOO 1000 ML",
  },
  {
    id: "vs16012",
    name: "SOFTENING SHAMPOO 250 ML",
    brand: "VERSUM 2.0",
    price: 11585,
    category: "shampoos",
    image: "/images/products/vs16012.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: SOFTENING SHAMPOO 250 ML",
  },
  {
    id: "vs16013",
    name: "REPAIRING MASK 1000 ML",
    brand: "VERSUM 2.0",
    price: 16801,
    category: "conditioners-masks",
    image: "/images/products/vs16013.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: REPAIRING MASK 1000 ML",
  },
  {
    id: "vs16014",
    name: "REPAIRING MASK 250 ML",
    brand: "VERSUM 2.0",
    price: 12906,
    category: "conditioners-masks",
    image: "/images/products/vs16014.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: REPAIRING MASK 250 ML",
  },
  {
    id: "vs16015",
    name: "NOURISHING MASK 1000 ML",
    brand: "VERSUM 2.0",
    price: 28002,
    category: "conditioners-masks",
    image: "/images/products/vs16015.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NOURISHING MASK 1000 ML",
  },
  {
    id: "vs16016",
    name: "NOURISHING MASK 250 ML",
    brand: "VERSUM 2.0",
    price: 12906,
    category: "conditioners-masks",
    image: "/images/products/vs16016.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NOURISHING MASK 250 ML",
  },
  {
    id: "vs16017",
    name: "ANTI-FRIZZ MASK 1000 ML",
    brand: "VERSUM 2.0",
    price: 28002,
    category: "conditioners-masks",
    image: "/images/products/vs16017.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: ANTI-FRIZZ MASK 1000 ML",
  },
  {
    id: "vs16018",
    name: "ANTI-FRIZZ MASK 250 ML",
    brand: "VERSUM 2.0",
    price: 12906,
    category: "conditioners-masks",
    image: "/images/products/vs16018.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: ANTI-FRIZZ MASK 250 ML",
  },
  {
    id: "vs16001",
    name: "MOISTURIZING SHAMPOO 1000 ML",
    brand: "VERSUM 2.0",
    price: 26225,
    category: "shampoos",
    image: "/images/products/vs16001.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: MOISTURIZING SHAMPOO 1000 ML",
  },
  {
    id: "vs16002",
    name: "MOISTURIZING SHAMPOO 250 ML",
    brand: "VERSUM 2.0",
    price: 12011,
    category: "shampoos",
    image: "/images/products/vs16002.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: MOISTURIZING SHAMPOO 250 ML",
  },
  {
    id: "vs16003",
    name: "MOISTURIZING MASK 1000 ML",
    brand: "VERSUM 2.0",
    price: 28002,
    category: "conditioners-masks",
    image: "/images/products/vs16003.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: MOISTURIZING MASK 1000 ML",
  },
  {
    id: "vs16004",
    name: "MOISTURIZING MASK 250 ML",
    brand: "VERSUM 2.0",
    price: 12906,
    category: "conditioners-masks",
    image: "/images/products/vs16004.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: MOISTURIZING MASK 250 ML",
  },
  {
    id: "vs16005",
    name: "AGE DEFYING SHAMPOO 1000 ML",
    brand: "VERSUM 2.0",
    price: 26225,
    category: "shampoos",
    image: "/images/products/vs16005.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: AGE DEFYING SHAMPOO 1000 ML",
  },
  {
    id: "vs16006",
    name: "AGE DEFYING SHAMPOO 250 ML",
    brand: "VERSUM 2.0",
    price: 12011,
    category: "shampoos",
    image: "/images/products/vs16006.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: AGE DEFYING SHAMPOO 250 ML",
  },
  {
    id: "vs16007",
    name: "AGE DEFYING MASK 1000 ML",
    brand: "VERSUM 2.0",
    price: 28002,
    category: "conditioners-masks",
    image: "/images/products/vs16007.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: AGE DEFYING MASK 1000 ML",
  },
  {
    id: "vs16008",
    name: "AGE DEFYING MASK 250 ML",
    brand: "VERSUM 2.0",
    price: 12906,
    category: "conditioners-masks",
    image: "/images/products/vs16008.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: AGE DEFYING MASK 250 ML",
  },
  {
    id: "vs16009",
    name: "AGE DEFYING LAMELLAR ELIXIR 90 ML",
    brand: "VERSUM 2.0",
    price: 25344,
    category: "treatments-serums",
    image: "/images/products/vs16009.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: AGE DEFYING LAMELLAR ELIXIR 90 ML",
  },
  {
    id: "vs16010",
    name: "AGE DEFYING LAMELLAR ELIXIR 9 X 7 ML",
    brand: "VERSUM 2.0",
    price: 36246,
    category: "treatments-serums",
    image: "/images/products/vs16010.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: AGE DEFYING LAMELLAR ELIXIR 9 X 7 ML",
  },
  {
    id: "vs16020",
    name: "DETANGLING DUAL PHASE LEAVE- IN",
    brand: "VERSUM 2.0",
    price: 18052,
    category: "other",
    image: "/images/products/vs16020.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: DETANGLING DUAL PHASE LEAVE- IN",
  },
  {
    id: "vs16021",
    name: "MULTI ACTION 15IN1 150 ML",
    brand: "VERSUM 2.0",
    price: 18052,
    category: "other",
    image: "/images/products/vs16021.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: MULTI ACTION 15IN1 150 ML",
  },
  {
    id: "vs16022",
    name: "CONDITIONING LEAVE-IN CREAM 250 ML",
    brand: "VERSUM 2.0",
    price: 14399,
    category: "styling-finishing",
    image: "/images/products/vs16022.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: CONDITIONING LEAVE-IN CREAM 250 ML",
  },
  {
    id: "vs16023",
    name: "NORMALIZING PEELING 150 ML",
    brand: "VERSUM 2.0",
    price: 20085,
    category: "other",
    image: "/images/products/vs16023.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NORMALIZING PEELING 150 ML",
  },
  {
    id: "vs16024",
    name: "NORMALIZING SHAMPOO 1000 ML",
    brand: "VERSUM 2.0",
    price: 33759,
    category: "shampoos",
    image: "/images/products/vs16024.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NORMALIZING SHAMPOO 1000 ML",
  },
  {
    id: "vs16025",
    name: "NORMALIZING SHAMPOO 250 ML",
    brand: "VERSUM 2.0",
    price: 14854,
    category: "shampoos",
    image: "/images/products/vs16025.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NORMALIZING SHAMPOO 250 ML",
  },
  {
    id: "vs16026",
    name: "NORMALIZING TREATMENT 1000 ML",
    brand: "VERSUM 2.0",
    price: 31982,
    category: "treatments-serums",
    image: "/images/products/vs16026.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: NORMALIZING TREATMENT 1000 ML",
  },
  {
    id: "vs16027",
    name: "NORMALIZING TREATMENT 250 ML",
    brand: "VERSUM 2.0",
    price: 14854,
    category: "treatments-serums",
    image: "/images/products/vs16027.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: NORMALIZING TREATMENT 250 ML",
  },
  {
    id: "vs16028",
    name: "REINFORCING SHAMPOO 1000 ML",
    brand: "VERSUM 2.0",
    price: 30745,
    category: "shampoos",
    image: "/images/products/vs16028.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: REINFORCING SHAMPOO 1000 ML",
  },
  {
    id: "vs16029",
    name: "REINFORCING SHAMPOO 250 ML",
    brand: "VERSUM 2.0",
    price: 13788,
    category: "shampoos",
    image: "/images/products/vs16029.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: REINFORCING SHAMPOO 250 ML",
  },
  {
    id: "vs16031",
    name: "reinforcing lotion 9 x 7 ml",
    brand: "VERSUM 2.0",
    price: 36175,
    category: "treatments-serums",
    image: "/images/products/vs16031.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: reinforcing lotion 9 x 7 ml",
  },
  {
    id: "vs16041",
    name: "RECONSTRUCTING SHAMPOO 1000 ML",
    brand: "VERSUM 2.0",
    price: 40695,
    category: "shampoos",
    image: "/images/products/vs16041.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: RECONSTRUCTING SHAMPOO 1000 ML",
  },
  {
    id: "vs16042",
    name: "RECONSTRUCTING SHAMPOO 250 ML",
    brand: "VERSUM 2.0",
    price: 14399,
    category: "shampoos",
    image: "/images/products/vs16042.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: RECONSTRUCTING SHAMPOO 250 ML",
  },
  {
    id: "vs16043",
    name: "RECONSTRUCTING FILLER 9X20 ML",
    brand: "VERSUM 2.0",
    price: 63367,
    category: "other",
    image: "/images/products/vs16043.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: RECONSTRUCTING FILLER 9X20 ML",
  },
  {
    id: "vs16044",
    name: "RECONSTRUCTING TREATMENT 1000 ML",
    brand: "VERSUM 2.0",
    price: 104119,
    category: "treatments-serums",
    image: "/images/products/vs16044.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: RECONSTRUCTING TREATMENT 1000 ML",
  },
  {
    id: "vs16045",
    name: "RECONSTRUCTING FINALIZER 1000 ML",
    brand: "VERSUM 2.0",
    price: 54298,
    category: "other",
    image: "/images/products/vs16045.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: RECONSTRUCTING FINALIZER 1000 ML",
  },
  {
    id: "vs16046",
    name: "RECONSTRUCTING FINALIZER 250 ML",
    brand: "VERSUM 2.0",
    price: 18308,
    category: "other",
    image: "/images/products/vs16046.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: RECONSTRUCTING FINALIZER 250 ML",
  },
  {
    id: "s98-00",
    name: "BOTULINO EFFECT 50 ML + 150 ML",
    brand: "VERSUM 2.0",
    price: 59813,
    category: "other",
    image: "/images/products/s98-00.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: BOTULINO EFFECT 50 ML + 150 ML",
  },
  {
    id: "vs16032",
    name: "PERFORMING SHAMPOO 1000 ML",
    brand: "VERSUM 2.0",
    price: 26225,
    category: "shampoos",
    image: "/images/products/vs16032.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: PERFORMING SHAMPOO 1000 ML",
  },
  {
    id: "vs16033",
    name: "PERFORMING SHAMPOO 250 ML",
    brand: "VERSUM 2.0",
    price: 12011,
    category: "shampoos",
    image: "/images/products/vs16033.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: PERFORMING SHAMPOO 250 ML",
  },
  {
    id: "vs16034",
    name: "PERFORMING MASK 1000 ML",
    brand: "VERSUM 2.0",
    price: 28002,
    category: "conditioners-masks",
    image: "/images/products/vs16034.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: PERFORMING MASK 1000 ML",
  },
  {
    id: "vs16035",
    name: "PERFORMING MASK 250 ML",
    brand: "VERSUM 2.0",
    price: 12906,
    category: "conditioners-masks",
    image: "/images/products/vs16035.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: PERFORMING MASK 250 ML",
  },
  {
    id: "vs16036",
    name: "EXTRA SILVER SHAMPOO 250 ML",
    brand: "VERSUM 2.0",
    price: 12011,
    category: "shampoos",
    image: "/images/products/vs16036.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: EXTRA SILVER SHAMPOO 250 ML",
  },
  {
    id: "vs16037",
    name: "EXTRA SILVER SHAMPOO 1000 ML",
    brand: "VERSUM 2.0",
    price: 26225,
    category: "shampoos",
    image: "/images/products/vs16037.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: EXTRA SILVER SHAMPOO 1000 ML",
  },
  {
    id: "vs16038",
    name: "PREPARING SHAMPOO 1000 ML",
    brand: "VERSUM 2.0",
    price: 26225,
    category: "shampoos",
    image: "/images/products/vs16038.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: PREPARING SHAMPOO 1000 ML",
  },
  {
    id: "vs16039",
    name: "MAINTAINING SHAMPOO 250 ML",
    brand: "VERSUM 2.0",
    price: 12011,
    category: "shampoos",
    image: "/images/products/vs16039.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: MAINTAINING SHAMPOO 250 ML",
  },
  {
    id: "vs16040",
    name: "MAINTAINING MASK 250 ML",
    brand: "VERSUM 2.0",
    price: 12906,
    category: "conditioners-masks",
    image: "/images/products/vs16040.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: MAINTAINING MASK 250 ML",
  },
  {
    id: "vs26200",
    name: "HAIR SPRAY STRONG 500 ML",
    brand: "VERSUM 2.0",
    price: 13503,
    category: "styling-finishing",
    image: "/images/products/vs26200.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: HAIR SPRAY STRONG 500 ML",
  },
  {
    id: "vs26201",
    name: "ECO HAIR SPRAY 300 ML",
    brand: "VERSUM 2.0",
    price: 19019,
    category: "styling-finishing",
    image: "/images/products/vs26201.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: ECO HAIR SPRAY 300 ML",
  },
  {
    id: "vs26202",
    name: "POLISHING SPRAY 150 ML",
    brand: "VERSUM 2.0",
    price: 22743,
    category: "styling-finishing",
    image: "/images/products/vs26202.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: POLISHING SPRAY 150 ML",
  },
  {
    id: "vs26203",
    name: "THERMAL PROTECTOR 300 ML",
    brand: "VERSUM 2.0",
    price: 18948,
    category: "other",
    image: "/images/products/vs26203.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: THERMAL PROTECTOR 300 ML",
  },
  {
    id: "vs26204",
    name: "STRONG HOLD MOUSSE 300 ML",
    brand: "VERSUM 2.0",
    price: 17171,
    category: "styling-finishing",
    image: "/images/products/vs26204.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: STRONG HOLD MOUSSE 300 ML",
  },
  {
    id: "vs26206",
    name: "VOLUME BOOSTER 150 ML",
    brand: "VERSUM 2.0",
    price: 11656,
    category: "technical-coloring",
    image: "/images/products/vs26206.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: VOLUME BOOSTER 150 ML",
  },
  {
    id: "vs26212",
    name: "MEDITERRANEAN OIL 100 ML",
    brand: "VERSUM 2.0",
    price: 27121,
    category: "treatments-serums",
    image: "/images/products/vs26212.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: MEDITERRANEAN OIL 100 ML",
  },
  {
    id: "vs26213",
    name: "CRYSTAL DROPS 100 ML",
    brand: "VERSUM 2.0",
    price: 24448,
    category: "other",
    image: "/images/products/vs26213.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: CRYSTAL DROPS 100 ML",
  },
  {
    id: "vs45127",
    name: "CURLS DEFINER 100 ML",
    brand: "VERSUM 2.0",
    price: 14399,
    category: "styling-finishing",
    image: "/images/products/vs45127.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: CURLS DEFINER 100 ML",
  },
  {
    id: "vs26021",
    name: "EMULSION CREAM 10 VOLUME 3% 1000 ML",
    brand: "VERSUM 2.0",
    price: 8998,
    category: "styling-finishing",
    image: "/images/products/vs26021.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: EMULSION CREAM 10 VOLUME 3% 1000 ML",
  },
  {
    id: "vs26022",
    name: "EMULSION CREAM 20 VOLUME 6% 1000 ML",
    brand: "VERSUM 2.0",
    price: 8998,
    category: "styling-finishing",
    image: "/images/products/vs26022.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: EMULSION CREAM 20 VOLUME 6% 1000 ML",
  },
  {
    id: "vs26023",
    name: "EMULSION CREAM 30 VOLUME 9% 1000 ML",
    brand: "VERSUM 2.0",
    price: 8998,
    category: "styling-finishing",
    image: "/images/products/vs26023.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: EMULSION CREAM 30 VOLUME 9% 1000 ML",
  },
  {
    id: "vs26024",
    name: "EMULSION CREAM 40 VOLUME 12% 1000 ML",
    brand: "VERSUM 2.0",
    price: 8998,
    category: "styling-finishing",
    image: "/images/products/vs26024.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: EMULSION CREAM 40 VOLUME 12% 1000 ML",
  },
  {
    id: "s81-00",
    name: "GRADIENT SILVER MASK 280ML",
    brand: "VERSUM 2.0",
    price: 18592,
    category: "conditioners-masks",
    image: "/images/products/s81-00.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: GRADIENT SILVER MASK 280ML",
  },
  {
    id: "s82-00",
    name: "GRADIENT CARAMEL MASK 280ML",
    brand: "VERSUM 2.0",
    price: 18592,
    category: "conditioners-masks",
    image: "/images/products/s82-00.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: GRADIENT CARAMEL MASK 280ML",
  },
  {
    id: "s83-00",
    name: "GRADIENT RED MASK 280ML",
    brand: "VERSUM 2.0",
    price: 18592,
    category: "conditioners-masks",
    image: "/images/products/s83-00.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: GRADIENT RED MASK 280ML",
  },
  {
    id: "s84-00",
    name: "GRADIENT BEIGE MASK 280ML",
    brand: "VERSUM 2.0",
    price: 18592,
    category: "conditioners-masks",
    image: "/images/products/s84-00.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: GRADIENT BEIGE MASK 280ML",
  },
  {
    id: "s85-00",
    name: "GRADIENT CHOCOLATE MASK 280ML",
    brand: "VERSUM 2.0",
    price: 18592,
    category: "conditioners-masks",
    image: "/images/products/s85-00.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: GRADIENT CHOCOLATE MASK 280ML",
  },
  {
    id: "s86-00",
    name: "GRADIENT BLACK MASK 280ML",
    brand: "VERSUM 2.0",
    price: 18592,
    category: "conditioners-masks",
    image: "/images/products/s86-00.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: GRADIENT BLACK MASK 280ML",
  },
  {
    id: "s87-00",
    name: "GRADIENT GOLD MASK 280ML",
    brand: "VERSUM 2.0",
    price: 18592,
    category: "conditioners-masks",
    image: "/images/products/s87-00.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: GRADIENT GOLD MASK 280ML",
  },
  {
    id: "s88-00",
    name: "GRADIENT COPPER MASK 280ML",
    brand: "VERSUM 2.0",
    price: 18592,
    category: "conditioners-masks",
    image: "/images/products/s88-00.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: GRADIENT COPPER MASK 280ML",
  },
  {
    id: "s89-00",
    name: "GRADIENT VIOLET MASK 280ML",
    brand: "VERSUM 2.0",
    price: 18592,
    category: "conditioners-masks",
    image: "/images/products/s89-00.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: GRADIENT VIOLET MASK 280ML",
  },
  {
    id: "vs16019",
    name: "SOFTENING BOOST FIVE SECRETS OIL 4 X 20 ML",
    brand: "VERSUM 2.0",
    price: 32522,
    category: "treatments-serums",
    image: "/images/products/vs16019.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: SOFTENING BOOST FIVE SECRETS OIL 4 X 20 ML",
  },
  {
    id: "GENUS",
    name: "KIT DECO AZUL PROF MANZANA 500 G",
    brand: "VERSUM 2.0",
    price: 55464,
    category: "other",
    image: "/images/products/GENUS.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: KIT DECO AZUL PROF MANZANA 500 G",
  },
  {
    id: "decowmelk",
    name: "KIT DECO BLANCA PROF MANZANA 500 G",
    brand: "VERSUM 2.0",
    price: 55464,
    category: "other",
    image: "/images/products/decowmelk.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: KIT DECO BLANCA PROF MANZANA 500 G",
  },
  {
    id: "decob9toni-k",
    name: "KIT DECO BLU 9 TONI COMPLETA 2X500G",
    brand: "VERSUM 2.0",
    price: 65343,
    category: "other",
    image: "/images/products/decob9toni-k.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: KIT DECO BLU 9 TONI COMPLETA 2X500G",
  },
  {
    id: "est45937",
    name: "ESTHESIA ABSOLUTE LENIS PROTEIN MAINTENANCE SHAMPOO",
    brand: "VERSUM 2.0",
    price: 26296,
    category: "shampoos",
    image: "/images/products/est45937.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: ESTHESIA ABSOLUTE LENIS PROTEIN MAINTENANCE SHAMPOO",
  },
  {
    id: "est45935",
    name: "ESTHESIA ABSOLUTE LENIS PROTEIN PREPARING SHAMPOO 500ML",
    brand: "VERSUM 2.0",
    price: 35294,
    category: "shampoos",
    image: "/images/products/est45935.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: ESTHESIA ABSOLUTE LENIS PROTEIN PREPARING SHAMPOO 500ML",
  },
  {
    id: "est45936",
    name: "ESTHESIA ABSOLUTE LENIS PROTEIN SPRAY 500ML",
    brand: "VERSUM 2.0",
    price: 169931,
    category: "styling-finishing",
    image: "/images/products/est45936.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: ESTHESIA ABSOLUTE LENIS PROTEIN SPRAY 500ML",
  },
  {
    id: "est45938",
    name: "ESTHESIA ABSOLUTE LENIS PROREIN MAINTENANCE MASK 250ML",
    brand: "VERSUM 2.0",
    price: 26296,
    category: "conditioners-masks",
    image: "/images/products/est45938.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: ESTHESIA ABSOLUTE LENIS PROREIN MAINTENANCE MASK 250ML",
  },
  {
    id: "m1-1-0",
    name: "VS NEGRO 1.0 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m1-1-0.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: VS NEGRO 1.0 100ML.",
  },
  {
    id: "m50-5-0",
    name: "VS LIGHT BROWN 5.0 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m50-5-0.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: VS LIGHT BROWN 5.0 100ML.",
  },
  {
    id: "m60-6-0",
    name: "VS DARK BLONDE 6.0 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m60-6-0.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: VS DARK BLONDE 6.0 100ML.",
  },
  {
    id: "m10-10-0",
    name: "VS BLONDE PLATINE 10.0 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m10-10-0.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: VS BLONDE PLATINE 10.0 100ML.",
  },
  {
    id: "m18-1-8",
    name: "VS BLUE BLACK 1.8 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m18-1-8.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: VS BLUE BLACK 1.8 100ML.",
  },
  {
    id: "m20-2-0",
    name: "VS DARKES BROWN 2.0 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m20-2-0.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: VS DARKES BROWN 2.0 100ML.",
  },
  {
    id: "m30-3-0",
    name: "VS DARK BROWN 3.0 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m30-3-0.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: VS DARK BROWN 3.0 100ML.",
  },
  {
    id: "m70-7-0",
    name: "VS BLONDE 7.0 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m70-7-0.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: VS BLONDE 7.0 100ML.",
  },
  {
    id: "m40-4-0",
    name: "VS BROWN 4.0 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m40-4-0.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: VS BROWN 4.0 100ML.",
  },
  {
    id: "m90-9-0",
    name: "VS VERY LIGHT BLONDE 9.0 100ML",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m90-9-0.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: VS VERY LIGHT BLONDE 9.0 100ML",
  },
  {
    id: "m80-8-0",
    name: "VS LIGHT BLONDE 8.0 100ML.",
    brand: "VERSUM 2.0",
    price: 9239,
    category: "other",
    image: "/images/products/m80-8-0.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: VS LIGHT BLONDE 8.0 100ML.",
  },
  {
    id: "1",
    name: "GENUS COLOR NATURAL",
    brand: "GENUS",
    price: 7036,
    category: "technical-coloring",
    image: "/images/products/1.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: GENUS COLOR NATURAL",
  },
  {
    id: "3",
    name: "ML OXY IN CREAM 20 VOL",
    brand: "GENUS",
    price: 7932,
    category: "technical-coloring",
    image: "/images/products/3.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: ML OXY IN CREAM 20 VOL",
  },
  {
    id: "4",
    name: "ML OXY IN CREAM 30 VOL",
    brand: "GENUS",
    price: 7932,
    category: "technical-coloring",
    image: "/images/products/4.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: ML OXY IN CREAM 30 VOL",
  },
  {
    id: "5",
    name: "ML OXY IN CREAM 40 VOL",
    brand: "GENUS",
    price: 7932,
    category: "technical-coloring",
    image: "/images/products/5.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: ML OXY IN CREAM 40 VOL",
  },
  {
    id: "6",
    name: "GENUS COLOR NATURAL",
    brand: "GENUS",
    price: 7036,
    category: "technical-coloring",
    image: "/images/products/6.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: GENUS COLOR NATURAL",
  },
  {
    id: "7",
    name: "GENUS COLOR NATURAL",
    brand: "GENUS",
    price: 7036,
    category: "technical-coloring",
    image: "/images/products/7.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: GENUS COLOR NATURAL",
  },
  {
    id: "8",
    name: "GENUS COLOR NATURA",
    brand: "GENUS",
    price: 7036,
    category: "technical-coloring",
    image: "/images/products/8.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: GENUS COLOR NATURA",
  },
  {
    id: "9",
    name: "GENUS COLOR NATURAL",
    brand: "GENUS",
    price: 7036,
    category: "technical-coloring",
    image: "/images/products/9.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: GENUS COLOR NATURAL",
  },
  {
    id: "blb",
    name: "GENUS BLUE BLEACH",
    brand: "GENUS",
    price: 24875,
    category: "other",
    image: "/images/products/blb.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: GENUS BLUE BLEACH",
  },
  {
    id: "blw",
    name: "GENUS WHITE BLEACH",
    brand: "GENUS",
    price: 24875,
    category: "other",
    image: "/images/products/blw.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: GENUS WHITE BLEACH",
  },
  {
    id: "s-9tone",
    name: "9 TONE AZUL 500ML",
    brand: "GENUS",
    price: 29139,
    category: "other",
    image: "/images/products/s-9tone.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: 9 TONE AZUL 500ML",
  },
  {
    id: "221",
    name: "SILVER SHAMPOO 300ML",
    brand: "GENUS",
    price: 8287,
    category: "shampoos",
    image: "/images/products/221.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: SILVER SHAMPOO 300ML",
  },
  {
    id: "222",
    name: "SILVER SHAMPOO 1000ML",
    brand: "GENUS",
    price: 15465,
    category: "shampoos",
    image: "/images/products/222.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: SILVER SHAMPOO 1000ML",
  },
  {
    id: "605",
    name: "HAIR DIRECT COLOR YELLOW",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/605.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR YELLOW",
  },
  {
    id: "606",
    name: "HAIR DIRECT COLOR ORANGE",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/606.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR ORANGE",
  },
  {
    id: "607",
    name: "HAIR DIRECT COLOR RED",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/607.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR RED",
  },
  {
    id: "608",
    name: "HAIR DIRECT COLOR PINK",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/608.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR PINK",
  },
  {
    id: "609",
    name: "HAIR DIRECT COLOR VIOLET",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/609.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR VIOLET",
  },
  {
    id: "610",
    name: "HAIR DIRECT COLOR BLUE",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/610.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR BLUE",
  },
  {
    id: "611",
    name: "HAIR DIRECT COLOR TURQUOISE",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/611.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR TURQUOISE",
  },
  {
    id: "612",
    name: "HAIR DIRECT COLOR GREEN",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/612.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR GREEN",
  },
  {
    id: "613",
    name: "HAIR DIRECT COLOR ACID GREEN",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/613.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR ACID GREEN",
  },
  {
    id: "614",
    name: "HAIR DIRECT COLOR WHITE",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/614.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR WHITE",
  },
  {
    id: "615",
    name: "HAIR DIRECT COLOR PEARL GREY",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/615.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR PEARL GREY",
  },
  {
    id: "616",
    name: "HAIR DIRECT COLOR CLEAR",
    brand: "GENUS",
    price: 15820,
    category: "technical-coloring",
    image: "/images/products/616.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: HAIR DIRECT COLOR CLEAR",
  },
  {
    id: "370",
    name: "1 SILVER COLORING MASK 200ML",
    brand: "GENUS",
    price: 13262,
    category: "conditioners-masks",
    image: "/images/products/370.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: 1 SILVER COLORING MASK 200ML",
  },
  {
    id: "371",
    name: "2 VIOLET COLORING MASK 200ML",
    brand: "GENUS",
    price: 13262,
    category: "conditioners-masks",
    image: "/images/products/371.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: 2 VIOLET COLORING MASK 200ML",
  },
  {
    id: "372",
    name: "3 CARAMEL COLORING MASK 200ML",
    brand: "GENUS",
    price: 13262,
    category: "conditioners-masks",
    image: "/images/products/372.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: 3 CARAMEL COLORING MASK 200ML",
  },
  {
    id: "373",
    name: "4 COPPER COLORING MASK 200ML",
    brand: "GENUS",
    price: 13262,
    category: "conditioners-masks",
    image: "/images/products/373.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: 4 COPPER COLORING MASK 200ML",
  },
  {
    id: "374",
    name: "5 BEIGE COLORING MASK 200ML",
    brand: "GENUS",
    price: 13262,
    category: "conditioners-masks",
    image: "/images/products/374.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: 5 BEIGE COLORING MASK 200ML",
  },
  {
    id: "375",
    name: "6 RED COLORING MASK 200ML",
    brand: "GENUS",
    price: 13262,
    category: "conditioners-masks",
    image: "/images/products/375.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: 6 RED COLORING MASK 200ML",
  },
  {
    id: "376",
    name: "7 CHOCOLATE COLORING MASK 200ML",
    brand: "GENUS",
    price: 13262,
    category: "conditioners-masks",
    image: "/images/products/376.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: 7 CHOCOLATE COLORING MASK 200ML",
  },
  {
    id: "214",
    name: "COLOR PROTECTION SHAMPOO 300ML",
    brand: "GENUS",
    price: 7391,
    category: "shampoos",
    image: "/images/products/214.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: COLOR PROTECTION SHAMPOO 300ML",
  },
  {
    id: "205",
    name: "COLOR PROTECTION SHAMPOO 1000ML",
    brand: "GENUS",
    price: 12267,
    category: "shampoos",
    image: "/images/products/205.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: COLOR PROTECTION SHAMPOO 1000ML",
  },
  {
    id: "239",
    name: "COLOR PROTECTION MASK 500ML",
    brand: "GENUS",
    price: 8457,
    category: "conditioners-masks",
    image: "/images/products/239.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: COLOR PROTECTION MASK 500ML",
  },
  {
    id: "215",
    name: "COLOR PROTECTION CONDITIONER 300ML",
    brand: "GENUS",
    price: 8287,
    category: "conditioners-masks",
    image: "/images/products/215.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: COLOR PROTECTION CONDITIONER 300ML",
  },
  {
    id: "206",
    name: "COLOR PROTECTION CONDITIONER 1000ML",
    brand: "GENUS",
    price: 12082,
    category: "conditioners-masks",
    image: "/images/products/206.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: COLOR PROTECTION CONDITIONER 1000ML",
  },
  {
    id: "250",
    name: "COLOR SEALING CREAM 200ML.",
    brand: "GENUS",
    price: 12722,
    category: "styling-finishing",
    image: "/images/products/250.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: COLOR SEALING CREAM 200ML.",
  },
  {
    id: "216",
    name: "MOISTURIZING SHAMPOO 300ML",
    brand: "GENUS",
    price: 11727,
    category: "shampoos",
    image: "/images/products/216.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: MOISTURIZING SHAMPOO 300ML",
  },
  {
    id: "207",
    name: "MOISTURIZING SHAMPOO 1000ML",
    brand: "GENUS",
    price: 17412,
    category: "shampoos",
    image: "/images/products/207.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: MOISTURIZING SHAMPOO 1000ML",
  },
  {
    id: "240",
    name: "MOISTURIZING MASK 500ML",
    brand: "GENUS",
    price: 14015,
    category: "conditioners-masks",
    image: "/images/products/240.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: MOISTURIZING MASK 500ML",
  },
  {
    id: "294",
    name: "MOISTURIZING MASK 1000ML",
    brand: "GENUS",
    price: 19388,
    category: "conditioners-masks",
    image: "/images/products/294.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: MOISTURIZING MASK 1000ML",
  },
  {
    id: "251",
    name: "MULTI-ACTION LEAVE-IN MASK 200ML",
    brand: "GENUS",
    price: 16872,
    category: "conditioners-masks",
    image: "/images/products/251.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: MULTI-ACTION LEAVE-IN MASK 200ML",
  },
  {
    id: "249",
    name: "MOISTURIZING SERUM 100ML",
    brand: "GENUS",
    price: 17171,
    category: "treatments-serums",
    image: "/images/products/249.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: MOISTURIZING SERUM 100ML",
  },
  {
    id: "217",
    name: "RESTRUCTURING SHAMPOO 300ML",
    brand: "GENUS",
    price: 7391,
    category: "shampoos",
    image: "/images/products/217.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: RESTRUCTURING SHAMPOO 300ML",
  },
  {
    id: "208",
    name: "RESTRUCTURING SHAMPOO 1000ML",
    brand: "GENUS",
    price: 12267,
    category: "shampoos",
    image: "/images/products/208.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: RESTRUCTURING SHAMPOO 1000ML",
  },
  {
    id: "241",
    name: "RESTRUCTURING MASK 500ML",
    brand: "GENUS",
    price: 8457,
    category: "conditioners-masks",
    image: "/images/products/241.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: RESTRUCTURING MASK 500ML",
  },
  {
    id: "295",
    name: "RESTRUCTURING MASK 1000ML",
    brand: "GENUS",
    price: 11727,
    category: "conditioners-masks",
    image: "/images/products/295.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: RESTRUCTURING MASK 1000ML",
  },
  {
    id: "265",
    name: "ANTI FRIZZ RESTRUCTURING CREAM 300ML",
    brand: "GENUS",
    price: 10845,
    category: "styling-finishing",
    image: "/images/products/265.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: ANTI FRIZZ RESTRUCTURING CREAM 300ML",
  },
  {
    id: "242",
    name: "SPLIT ENDS RESTRUCTURING TREATMENT 100ML",
    brand: "GENUS",
    price: 16275,
    category: "treatments-serums",
    image: "/images/products/242.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: SPLIT ENDS RESTRUCTURING TREATMENT 100ML",
  },
  {
    id: "243",
    name: "RESTRUCTURING LEAVE-IN LOTION 125ML",
    brand: "GENUS",
    price: 14399,
    category: "treatments-serums",
    image: "/images/products/243.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: RESTRUCTURING LEAVE-IN LOTION 125ML",
  },
  {
    id: "247",
    name: "RESTRUCTURING LEAVE-IN LOTION 12X10ML",
    brand: "GENUS",
    price: 19118,
    category: "treatments-serums",
    image: "/images/products/247.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: RESTRUCTURING LEAVE-IN LOTION 12X10ML",
  },
  {
    id: "291",
    name: "NOURISHING SHAMPOO 300ML",
    brand: "GENUS",
    price: 7391,
    category: "shampoos",
    image: "/images/products/291.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NOURISHING SHAMPOO 300ML",
  },
  {
    id: "209",
    name: "NOURISHING SHAMPOO 1000ML",
    brand: "GENUS",
    price: 12267,
    category: "shampoos",
    image: "/images/products/209.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NOURISHING SHAMPOO 1000ML",
  },
  {
    id: "292",
    name: "NOURISHING MASK 500ML",
    brand: "GENUS",
    price: 8457,
    category: "conditioners-masks",
    image: "/images/products/292.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NOURISHING MASK 500ML",
  },
  {
    id: "237",
    name: "NOURISHING MASK 1000ML",
    brand: "GENUS",
    price: 11727,
    category: "conditioners-masks",
    image: "/images/products/237.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NOURISHING MASK 1000ML",
  },
  {
    id: "288",
    name: "REVITALIZING GARLIC SHAMPOO 300ML",
    brand: "GENUS",
    price: 6510,
    category: "shampoos",
    image: "/images/products/288.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: REVITALIZING GARLIC SHAMPOO 300ML",
  },
  {
    id: "210",
    name: "REVITALIZING GARLIC SHAMPOO 1000ML",
    brand: "GENUS",
    price: 11840,
    category: "shampoos",
    image: "/images/products/210.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: REVITALIZING GARLIC SHAMPOO 1000ML",
  },
  {
    id: "238",
    name: "REVITALIZING GARLIC MASK 1000ML",
    brand: "GENUS",
    price: 11727,
    category: "conditioners-masks",
    image: "/images/products/238.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: REVITALIZING GARLIC MASK 1000ML",
  },
  {
    id: "218",
    name: "ENERGIZING SHAMPOO 300ML",
    brand: "GENUS",
    price: 7818,
    category: "shampoos",
    image: "/images/products/218.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: ENERGIZING SHAMPOO 300ML",
  },
  {
    id: "211",
    name: "ENERGIZING SHAMPOO 1000ML",
    brand: "GENUS",
    price: 13688,
    category: "shampoos",
    image: "/images/products/211.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: ENERGIZING SHAMPOO 1000ML",
  },
  {
    id: "266",
    name: "REINFORCING CLAY MASK 1000ML",
    brand: "GENUS",
    price: 19829,
    category: "conditioners-masks",
    image: "/images/products/266.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: REINFORCING CLAY MASK 1000ML",
  },
  {
    id: "245",
    name: "ENERGIZING LOTION 125ML",
    brand: "GENUS",
    price: 14399,
    category: "treatments-serums",
    image: "/images/products/245.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: ENERGIZING LOTION 125ML",
  },
  {
    id: "248",
    name: "ENERGIZING LOTION 12X10ML",
    brand: "GENUS",
    price: 19118,
    category: "treatments-serums",
    image: "/images/products/248.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: ENERGIZING LOTION 12X10ML",
  },
  {
    id: "246",
    name: "ENERGIZING CREN LOTION 125ML",
    brand: "GENUS",
    price: 14399,
    category: "treatments-serums",
    image: "/images/products/246.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: ENERGIZING CREN LOTION 125ML",
  },
  {
    id: "223",
    name: "INTENSE RESTORING SHAMPOO 300M",
    brand: "GENUS",
    price: 8998,
    category: "shampoos",
    image: "/images/products/223.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: INTENSE RESTORING SHAMPOO 300M",
  },
  {
    id: "224",
    name: "INTENSE RESTORING SHAMPOO 1000ML",
    brand: "GENUS",
    price: 17341,
    category: "shampoos",
    image: "/images/products/224.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: INTENSE RESTORING SHAMPOO 1000ML",
  },
  {
    id: "225",
    name: "INTENSE RESTORING MASK 500ML",
    brand: "GENUS",
    price: 13617,
    category: "conditioners-masks",
    image: "/images/products/225.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: INTENSE RESTORING MASK 500ML",
  },
  {
    id: "226",
    name: "INTENSE RESTORING MASK 1000ML",
    brand: "GENUS",
    price: 21790,
    category: "conditioners-masks",
    image: "/images/products/226.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: INTENSE RESTORING MASK 1000ML",
  },
  {
    id: "231",
    name: "INTENSE RESTORING FLUID OIL 200ML",
    brand: "GENUS",
    price: 21790,
    category: "treatments-serums",
    image: "/images/products/231.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: INTENSE RESTORING FLUID OIL 200ML",
  },
  {
    id: "227",
    name: "INTENSE RESTORING LOTION 12X10ML",
    brand: "GENUS",
    price: 28897,
    category: "treatments-serums",
    image: "/images/products/227.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: INTENSE RESTORING LOTION 12X10ML",
  },
  {
    id: "219",
    name: "BALANCING SHAMPOO 300ML",
    brand: "GENUS",
    price: 7818,
    category: "shampoos",
    image: "/images/products/219.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: BALANCING SHAMPOO 300ML",
  },
  {
    id: "212",
    name: "BALANCING SHAMPOO 1000ML",
    brand: "GENUS",
    price: 12267,
    category: "shampoos",
    image: "/images/products/212.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: BALANCING SHAMPOO 1000ML",
  },
  {
    id: "233",
    name: "PURIFYING SHAMPOO 300ML",
    brand: "GENUS",
    price: 7818,
    category: "shampoos",
    image: "/images/products/233.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: PURIFYING SHAMPOO 300ML",
  },
  {
    id: "213",
    name: "PURIFYING SHAMPOO 1000ML",
    brand: "GENUS",
    price: 15465,
    category: "shampoos",
    image: "/images/products/213.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: PURIFYING SHAMPOO 1000ML",
  },
  {
    id: "365",
    name: "LAMINESCENT SUPREME FILMER TREATMENT 200ML",
    brand: "GENUS",
    price: 20440,
    category: "treatments-serums",
    image: "/images/products/365.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: LAMINESCENT SUPREME FILMER TREATMENT 200ML",
  },
  {
    id: "366",
    name: "LAMINESCENT SUPREME FILMER SPRAY 100ML",
    brand: "GENUS",
    price: 14570,
    category: "styling-finishing",
    image: "/images/products/366.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: LAMINESCENT SUPREME FILMER SPRAY 100ML",
  },
  {
    id: "363",
    name: "24/7 PERPETUAL REPARING SYSTEM 50ML",
    brand: "GENUS",
    price: 20255,
    category: "other",
    image: "/images/products/363.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: 24/7 PERPETUAL REPARING SYSTEM 50ML",
  },
  {
    id: "273",
    name: "EXTRA STRONG HAIR SPRAY 500ML",
    brand: "GENUS",
    price: 9424,
    category: "styling-finishing",
    image: "/images/products/273.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: EXTRA STRONG HAIR SPRAY 500ML",
  },
  {
    id: "274",
    name: "GLOSSING SPRAY 115ML",
    brand: "GENUS",
    price: 14925,
    category: "styling-finishing",
    image: "/images/products/274.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: GLOSSING SPRAY 115ML",
  },
  {
    id: "275",
    name: "THERMAL PROTECTIVE SPRAY 150ML",
    brand: "GENUS",
    price: 15280,
    category: "styling-finishing",
    image: "/images/products/275.svg",
    rating: 4.6,
    description: "Professional Italian Hair Care: THERMAL PROTECTIVE SPRAY 150ML",
  },
  {
    id: "330",
    name: "EXTREME GEL 300ML",
    brand: "GENUS",
    price: 13077,
    category: "styling-finishing",
    image: "/images/products/330.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: EXTREME GEL 300ML",
  },
  {
    id: "359",
    name: "HYBRID SHAKE - 2-PHASE LEAVE-IN SPRAY 250ML",
    brand: "GENUS",
    price: 19829,
    category: "styling-finishing",
    image: "/images/products/359.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: HYBRID SHAKE - 2-PHASE LEAVE-IN SPRAY 250ML",
  },
  {
    id: "360",
    name: "SMOOTHING ELIXIR - SMOOTHING CREAM 150ML",
    brand: "GENUS",
    price: 12978,
    category: "treatments-serums",
    image: "/images/products/360.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: SMOOTHING ELIXIR - SMOOTHING CREAM 150ML",
  },
  {
    id: "361",
    name: "ABSOLUTE CURLS - CURLS DEFINER 100ML",
    brand: "GENUS",
    price: 16275,
    category: "styling-finishing",
    image: "/images/products/361.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: ABSOLUTE CURLS - CURLS DEFINER 100ML",
  },
  {
    id: "362",
    name: "LEAVE-IN ESSENCE - LEAVE-IN CONDITIONER 200ML",
    brand: "GENUS",
    price: 11727,
    category: "conditioners-masks",
    image: "/images/products/362.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: LEAVE-IN ESSENCE - LEAVE-IN CONDITIONER 200ML",
  },
  {
    id: "391",
    name: "NEW CATALOGUE - 2024 - IT/EN/ES",
    brand: "GENUS",
    price: 8529,
    category: "other",
    image: "/images/products/391.svg",
    rating: 4.5,
    description: "Professional Italian Hair Care: NEW CATALOGUE - 2024 - IT/EN/ES",
  },
  {
    id: "656",
    name: "GENUS EXPRESSION GLOSSY WAX 100ML",
    brand: "GENUS",
    price: 21677,
    category: "styling-finishing",
    image: "/images/products/656.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: GENUS EXPRESSION GLOSSY WAX 100ML",
  },
  {
    id: "gs-02",
    name: "PEROXIDE 10% VOL 1000ML.",
    brand: "GENUS",
    price: 8330,
    category: "technical-coloring",
    image: "/images/products/gs-02.svg",
    rating: 4.3,
    description: "Professional Italian Hair Care: PEROXIDE 10% VOL 1000ML.",
  },
  {
    id: "gs-03",
    name: "PEROXIDE 20% VOL. 1000ML.",
    brand: "GENUS",
    price: 8330,
    category: "technical-coloring",
    image: "/images/products/gs-03.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: PEROXIDE 20% VOL. 1000ML.",
  },
  {
    id: "gs-04",
    name: "PEROXIDE 30% VOL 1000ML.",
    brand: "GENUS",
    price: 8330,
    category: "technical-coloring",
    image: "/images/products/gs-04.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: PEROXIDE 30% VOL 1000ML.",
  },
  {
    id: "gs-05",
    name: "PEROXIDE 40% VOL 1000ML.",
    brand: "GENUS",
    price: 8330,
    category: "technical-coloring",
    image: "/images/products/gs-05.svg",
    rating: 4.4,
    description: "Professional Italian Hair Care: PEROXIDE 40% VOL 1000ML.",
  },
];
// 276 products total
