export interface Testimonial {
  id: number;
  name: string;
  initials: string;
  city: string;
  pureCity: string;
  brand: string;
  product: string;
  text: string;
  stars: number;
}

export const TESTIMONIALS: Testimonial[] = [
  {
    "id": 1,
    "name": "Fatima Abbasi",
    "initials": "FA",
    "city": "Faisalabad",
    "pureCity": "Faisalabad",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "Using VERSUM 2.0's range for 3 weeks now. My stylist in Faisalabad suggested it to fix dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair. The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  },
  {
    "id": 2,
    "name": "Shanza Farooqi",
    "initials": "SF",
    "city": "Gulberg III, Lahore",
    "pureCity": "Lahore",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "Honestly, I was skeptical because of the hard water, but the Harmonic Color is a miracle worker. Saved me from Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! Will definitely buy again!",
    "stars": 4
  },
  {
    "id": 3,
    "name": "Saad Dar",
    "initials": "SD",
    "city": "Gujranwala",
    "pureCity": "Gujranwala",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Using VERSUM 2.0's range for 3 weeks now. My stylist in Gujranwala suggested it to fix Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  },
  {
    "id": 4,
    "name": "Hania Malik",
    "initials": "HM",
    "city": "Rawalpindi",
    "pureCity": "Rawalpindi",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Best professional hair care available in Pakistan! Imported directly from Italy and the quality shows. It rescued my hair from the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. Highly recommended!",
    "stars": 5
  },
  {
    "id": 5,
    "name": "Maya Qureshi",
    "initials": "MQ",
    "city": "Gujranwala",
    "pureCity": "Gujranwala",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! and feels extremely nourishing. Worth every Rupee!",
    "stars": 4
  },
  {
    "id": 6,
    "name": "Alizeh Siddiqui",
    "initials": "AS",
    "city": "Sialkot",
    "pureCity": "Sialkot",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Honestly, I was skeptical because of the hard water, but the Oxygen Activator Cream is a miracle worker. Saved me from dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 7,
    "name": "Rabia Shah",
    "initials": "RS",
    "city": "Karachi",
    "pureCity": "Karachi",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated. This product restored the natural texture and shine beautifully.",
    "stars": 5
  },
  {
    "id": 8,
    "name": "Iqra Qureshi",
    "initials": "IQ",
    "city": "Multan",
    "pureCity": "Multan",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "Best professional hair care available in Pakistan! Imported directly from Italy and the quality shows. It rescued my hair from stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes. Highly recommended!",
    "stars": 4
  },
  {
    "id": 9,
    "name": "Fiza Abbasi",
    "initials": "FA",
    "city": "Rawalpindi",
    "pureCity": "Rawalpindi",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Hands down the best treatment for color-treated hair. The Mediterranean Oil healed my hair from split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly, and made the color look so rich and vibrant.",
    "stars": 5
  },
  {
    "id": 10,
    "name": "Yumna Ahmed",
    "initials": "YA",
    "city": "Rawalpindi",
    "pureCity": "Rawalpindi",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Shampoo",
    "text": "Hands down the best treatment for color-treated hair. The Reconstructing Shampoo healed my hair from dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing, and made the color look so rich and vibrant.",
    "stars": 5
  },
  {
    "id": 11,
    "name": "Anam Zafar",
    "initials": "AZ",
    "city": "Bahawalpur",
    "pureCity": "Bahawalpur",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 12,
    "name": "Usman Rehman",
    "initials": "UR",
    "city": "F-10 Markaz, Islamabad",
    "pureCity": "Islamabad",
    "brand": "GENUS",
    "product": "GENUS Anti-Frizz Serum",
    "text": "Hands down the best treatment for color-treated hair. The GENUS Anti-Frizz Serum healed my hair from stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes, and made the color look so rich and vibrant.",
    "stars": 4
  },
  {
    "id": 13,
    "name": "Yasir Javed",
    "initials": "YJ",
    "city": "F-8/2, Islamabad",
    "pureCity": "Islamabad",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Shampoo",
    "text": "Using MAXY LOOK's range for 3 weeks now. My stylist in Islamabad suggested it to fix the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  },
  {
    "id": 14,
    "name": "Nabeel Siddiqui",
    "initials": "NS",
    "city": "Peshawar",
    "pureCity": "Peshawar",
    "brand": "UNA",
    "product": "UNA Compensator Shampoo",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly. This product restored the natural texture and shine beautifully.",
    "stars": 4
  },
  {
    "id": 15,
    "name": "Mahnoor Mughal",
    "initials": "MM",
    "city": "Sialkot",
    "pureCity": "Sialkot",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Best professional hair care available in Pakistan! Imported directly from Italy and the quality shows. It rescued my hair from dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing. Highly recommended!",
    "stars": 5
  },
  {
    "id": 16,
    "name": "Omar Dar",
    "initials": "OD",
    "city": "Lahore",
    "pureCity": "Lahore",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Best professional hair care available in Pakistan! Imported directly from Italy and the quality shows. It rescued my hair from severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes. Highly recommended!",
    "stars": 5
  },
  {
    "id": 17,
    "name": "Sidra Qureshi",
    "initials": "SQ",
    "city": "Sargodha",
    "pureCity": "Sargodha",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Smells absolutely luxurious and keeps my hair fresh despite the sweat and dust. Fully addressed Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! 10/10 salon-grade quality.",
    "stars": 5
  },
  {
    "id": 18,
    "name": "Mahnoor Qureshi",
    "initials": "MQ",
    "city": "Abbottabad",
    "pureCity": "Abbottabad",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "The Oxygen Activator Cream has completely transformed my hair. I was struggling with dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 19,
    "name": "Mariam Abbasi",
    "initials": "MA",
    "city": "Quetta",
    "pureCity": "Quetta",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Using MAXY LOOK's range for 3 weeks now. My stylist in Quetta suggested it to fix severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes. The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  },
  {
    "id": 20,
    "name": "Sajal Gill",
    "initials": "SG",
    "city": "Abbottabad",
    "pureCity": "Abbottabad",
    "brand": "GENUS",
    "product": "GENUS Clarifying Shampoo",
    "text": "Honestly, I was skeptical because of the hard water, but the GENUS Clarifying Shampoo is a miracle worker. Saved me from heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated. Will definitely buy again!",
    "stars": 4
  },
  {
    "id": 21,
    "name": "Mawra Ansari",
    "initials": "MA",
    "city": "Hyderabad",
    "pureCity": "Hyderabad",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 22,
    "name": "Rabia Siddiqui",
    "initials": "RS",
    "city": "Multan",
    "pureCity": "Multan",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Shampoo",
    "text": "Honestly, I was skeptical because of the hard water, but the Reconstructing Shampoo is a miracle worker. Saved me from dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 23,
    "name": "Amna Javed",
    "initials": "AJ",
    "city": "Karachi",
    "pureCity": "Karachi",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Honestly, I was skeptical because of the hard water, but the UNA Hair Treatment is a miracle worker. Saved me from the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 24,
    "name": "Zain Raza",
    "initials": "ZR",
    "city": "Islamabad",
    "pureCity": "Islamabad",
    "brand": "GENUS",
    "product": "GENUS Clarifying Shampoo",
    "text": "Honestly, I was skeptical because of the hard water, but the GENUS Clarifying Shampoo is a miracle worker. Saved me from split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 25,
    "name": "Zain Sheikh",
    "initials": "ZS",
    "city": "PECHS, Karachi",
    "pureCity": "Karachi",
    "brand": "UNA",
    "product": "UNA Compensator Shampoo",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 26,
    "name": "Amna Ansari",
    "initials": "AA",
    "city": "Bahawalpur",
    "pureCity": "Bahawalpur",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Honestly, I was skeptical because of the hard water, but the UNA Hair Treatment is a miracle worker. Saved me from the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 27,
    "name": "Fiza Dar",
    "initials": "FD",
    "city": "E-7, Islamabad",
    "pureCity": "Islamabad",
    "brand": "GENUS",
    "product": "Compact Bleaching Powder",
    "text": "Best professional hair care available in Pakistan! Imported directly from Italy and the quality shows. It rescued my hair from dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair. Highly recommended!",
    "stars": 5
  },
  {
    "id": 28,
    "name": "Amna Sharif",
    "initials": "AS",
    "city": "Sialkot",
    "pureCity": "Sialkot",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Shampoo",
    "text": "Honestly, I was skeptical because of the hard water, but the Reconstructing Shampoo is a miracle worker. Saved me from the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 29,
    "name": "Waleed Mirza",
    "initials": "WM",
    "city": "Rawalpindi",
    "pureCity": "Rawalpindi",
    "brand": "UNA",
    "product": "UNA Compensator Shampoo",
    "text": "Using UNA's range for 3 weeks now. My stylist in Rawalpindi suggested it to fix Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  },
  {
    "id": 30,
    "name": "Alizeh Rehman",
    "initials": "AR",
    "city": "Sargodha",
    "pureCity": "Sargodha",
    "brand": "GENUS",
    "product": "Compact Bleaching Powder",
    "text": "Hands down the best treatment for color-treated hair. The Compact Bleaching Powder healed my hair from stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes, and made the color look so rich and vibrant.",
    "stars": 4
  },
  {
    "id": 31,
    "name": "Usman Chaudhry",
    "initials": "UC",
    "city": "Faisalabad",
    "pureCity": "Faisalabad",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "The Harmonic Color has completely transformed my hair. I was struggling with Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 32,
    "name": "Amna Zafar",
    "initials": "AZ",
    "city": "Quetta",
    "pureCity": "Quetta",
    "brand": "GENUS",
    "product": "GENUS Anti-Frizz Serum",
    "text": "The GENUS Anti-Frizz Serum has completely transformed my hair. I was struggling with severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 4
  },
  {
    "id": 33,
    "name": "Sadia Siddiqui",
    "initials": "SS",
    "city": "Gujranwala",
    "pureCity": "Gujranwala",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Hands down the best treatment for color-treated hair. The Reconstructing Mask healed my hair from dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair, and made the color look so rich and vibrant.",
    "stars": 5
  },
  {
    "id": 34,
    "name": "Shanza Iqbal",
    "initials": "SI",
    "city": "Johar Town, Lahore",
    "pureCity": "Lahore",
    "brand": "GENUS",
    "product": "GENUS Clarifying Shampoo",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing. This product restored the natural texture and shine beautifully.",
    "stars": 5
  },
  {
    "id": 35,
    "name": "Nida Rehman",
    "initials": "NR",
    "city": "Peshawar",
    "pureCity": "Peshawar",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 36,
    "name": "Ayesha Dar",
    "initials": "AD",
    "city": "Gujranwala",
    "pureCity": "Gujranwala",
    "brand": "GENUS",
    "product": "GENUS Clarifying Shampoo",
    "text": "Best professional hair care available in Pakistan! Imported directly from Italy and the quality shows. It rescued my hair from the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. Highly recommended!",
    "stars": 4
  },
  {
    "id": 37,
    "name": "Neelum Rehman",
    "initials": "NR",
    "city": "Islamabad",
    "pureCity": "Islamabad",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Smells absolutely luxurious and keeps my hair fresh despite the sweat and dust. Fully addressed dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair. 10/10 salon-grade quality.",
    "stars": 5
  },
  {
    "id": 38,
    "name": "Rameen Raza",
    "initials": "RR",
    "city": "Bahawalpur",
    "pureCity": "Bahawalpur",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! This product restored the natural texture and shine beautifully.",
    "stars": 5
  },
  {
    "id": 39,
    "name": "Sajal Sheikh",
    "initials": "SS",
    "city": "Karachi",
    "pureCity": "Karachi",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes. This product restored the natural texture and shine beautifully.",
    "stars": 4
  },
  {
    "id": 40,
    "name": "Ayeza Chaudhry",
    "initials": "AC",
    "city": "Hyderabad",
    "pureCity": "Hyderabad",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly. This product restored the natural texture and shine beautifully.",
    "stars": 5
  },
  {
    "id": 41,
    "name": "Zoya Rehman",
    "initials": "ZR",
    "city": "Gulberg III, Lahore",
    "pureCity": "Lahore",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes, and feels extremely nourishing. Worth every Rupee!",
    "stars": 4
  },
  {
    "id": 42,
    "name": "Shahrukh Khan",
    "initials": "SK",
    "city": "Clifton Block 4, Karachi",
    "pureCity": "Karachi",
    "brand": "GENUS",
    "product": "GENUS Anti-Frizz Serum",
    "text": "Smells absolutely luxurious and keeps my hair fresh despite the sweat and dust. Fully addressed Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! 10/10 salon-grade quality.",
    "stars": 4
  },
  {
    "id": 43,
    "name": "Zoya Malik",
    "initials": "ZM",
    "city": "DHA Phase 6, Lahore",
    "pureCity": "Lahore",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Honestly, I was skeptical because of the hard water, but the UNA Hair Treatment is a miracle worker. Saved me from dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 44,
    "name": "Komal Farooqi",
    "initials": "KF",
    "city": "Gujranwala",
    "pureCity": "Gujranwala",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Using VERSUM 2.0's range for 3 weeks now. My stylist in Gujranwala suggested it to fix dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair. The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  },
  {
    "id": 45,
    "name": "Ali Butt",
    "initials": "AB",
    "city": "Bahawalpur",
    "pureCity": "Bahawalpur",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Honestly, I was skeptical because of the hard water, but the UNA Hair Treatment is a miracle worker. Saved me from heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 46,
    "name": "Hira Ansari",
    "initials": "HA",
    "city": "Abbottabad",
    "pureCity": "Abbottabad",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Shampoo",
    "text": "Honestly, I was skeptical because of the hard water, but the Reconstructing Shampoo is a miracle worker. Saved me from split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 47,
    "name": "Yasir Shah",
    "initials": "YS",
    "city": "Abbottabad",
    "pureCity": "Abbottabad",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "The Harmonic Color has completely transformed my hair. I was struggling with dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 48,
    "name": "Farhan Rehman",
    "initials": "FR",
    "city": "Abbottabad",
    "pureCity": "Abbottabad",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Smells absolutely luxurious and keeps my hair fresh despite the sweat and dust. Fully addressed stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes. 10/10 salon-grade quality.",
    "stars": 4
  },
  {
    "id": 49,
    "name": "Mustafa Raza",
    "initials": "MR",
    "city": "Multan",
    "pureCity": "Multan",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Shampoo",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. This product restored the natural texture and shine beautifully.",
    "stars": 5
  },
  {
    "id": 50,
    "name": "Zainab Sheikh",
    "initials": "ZS",
    "city": "Gujranwala",
    "pureCity": "Gujranwala",
    "brand": "UNA",
    "product": "UNA Compensator Shampoo",
    "text": "Smells absolutely luxurious and keeps my hair fresh despite the sweat and dust. Fully addressed dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing. 10/10 salon-grade quality.",
    "stars": 5
  },
  {
    "id": 51,
    "name": "Alizeh Zafar",
    "initials": "AZ",
    "city": "Rawalpindi",
    "pureCity": "Rawalpindi",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Hands down the best treatment for color-treated hair. The Oxygen Activator Cream healed my hair from Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! and made the color look so rich and vibrant.",
    "stars": 5
  },
  {
    "id": 52,
    "name": "Kubra Farooqi",
    "initials": "KF",
    "city": "Karachi",
    "pureCity": "Karachi",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Best professional hair care available in Pakistan! Imported directly from Italy and the quality shows. It rescued my hair from dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing. Highly recommended!",
    "stars": 5
  },
  {
    "id": 53,
    "name": "Buraq Hashmi",
    "initials": "BH",
    "city": "Peshawar",
    "pureCity": "Peshawar",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Honestly, I was skeptical because of the hard water, but the Oxygen Activator Cream is a miracle worker. Saved me from severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 54,
    "name": "Mustafa Abbasi",
    "initials": "MA",
    "city": "E-7, Islamabad",
    "pureCity": "Islamabad",
    "brand": "UNA",
    "product": "UNA Compensator Shampoo",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! This product restored the natural texture and shine beautifully.",
    "stars": 5
  },
  {
    "id": 55,
    "name": "Zoya Zafar",
    "initials": "ZZ",
    "city": "Gujranwala",
    "pureCity": "Gujranwala",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 56,
    "name": "Neelum Mirza",
    "initials": "NM",
    "city": "Sargodha",
    "pureCity": "Sargodha",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. This product restored the natural texture and shine beautifully.",
    "stars": 4
  },
  {
    "id": 57,
    "name": "Mariam Javed",
    "initials": "MJ",
    "city": "Hyderabad",
    "pureCity": "Hyderabad",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Honestly, I was skeptical because of the hard water, but the Oxygen Activator Cream is a miracle worker. Saved me from dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 58,
    "name": "Zainab Javed",
    "initials": "ZJ",
    "city": "Quetta",
    "pureCity": "Quetta",
    "brand": "GENUS",
    "product": "GENUS Clarifying Shampoo",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 59,
    "name": "Alizeh Mirza",
    "initials": "AM",
    "city": "Peshawar",
    "pureCity": "Peshawar",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "The Harmonic Color has completely transformed my hair. I was struggling with severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 60,
    "name": "Saad Butt",
    "initials": "SB",
    "city": "Sargodha",
    "pureCity": "Sargodha",
    "brand": "GENUS",
    "product": "GENUS Anti-Frizz Serum",
    "text": "The GENUS Anti-Frizz Serum has completely transformed my hair. I was struggling with split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 4
  },
  {
    "id": 61,
    "name": "Mahnoor Dar",
    "initials": "MD",
    "city": "Islamabad",
    "pureCity": "Islamabad",
    "brand": "GENUS",
    "product": "GENUS Anti-Frizz Serum",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing, and feels extremely nourishing. Worth every Rupee!",
    "stars": 4
  },
  {
    "id": 62,
    "name": "Raza Raza",
    "initials": "RR",
    "city": "Quetta",
    "pureCity": "Quetta",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 63,
    "name": "Hania Gill",
    "initials": "HG",
    "city": "Quetta",
    "pureCity": "Quetta",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 64,
    "name": "Nida Rehman",
    "initials": "NR",
    "city": "Multan",
    "pureCity": "Multan",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Using UNA's range for 3 weeks now. My stylist in Multan suggested it to fix the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  },
  {
    "id": 65,
    "name": "Alizeh Lodi",
    "initials": "AL",
    "city": "Islamabad",
    "pureCity": "Islamabad",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Hands down the best treatment for color-treated hair. The Reconstructing Mask healed my hair from heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated, and made the color look so rich and vibrant.",
    "stars": 5
  },
  {
    "id": 66,
    "name": "Daniyal Ahmed",
    "initials": "DA",
    "city": "Rawalpindi",
    "pureCity": "Rawalpindi",
    "brand": "UNA",
    "product": "UNA Compensator Shampoo",
    "text": "The UNA Compensator Shampoo has completely transformed my hair. I was struggling with heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 4
  },
  {
    "id": 67,
    "name": "Waleed Khan",
    "initials": "WK",
    "city": "Multan",
    "pureCity": "Multan",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Hands down the best treatment for color-treated hair. The Oxygen Activator Cream healed my hair from heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated, and made the color look so rich and vibrant.",
    "stars": 4
  },
  {
    "id": 68,
    "name": "Rimsha Javed",
    "initials": "RJ",
    "city": "Faisalabad",
    "pureCity": "Faisalabad",
    "brand": "UNA",
    "product": "UNA Compensator Shampoo",
    "text": "The UNA Compensator Shampoo has completely transformed my hair. I was struggling with split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 69,
    "name": "Saira Abbasi",
    "initials": "SA",
    "city": "Islamabad",
    "pureCity": "Islamabad",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Hands down the best treatment for color-treated hair. The Mediterranean Oil healed my hair from Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! and made the color look so rich and vibrant.",
    "stars": 4
  },
  {
    "id": 70,
    "name": "Mariam Sharif",
    "initials": "MS",
    "city": "Peshawar",
    "pureCity": "Peshawar",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Using VERSUM 2.0's range for 3 weeks now. My stylist in Peshawar suggested it to fix split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly. The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  },
  {
    "id": 71,
    "name": "Alizeh Hashmi",
    "initials": "AH",
    "city": "Rawalpindi",
    "pureCity": "Rawalpindi",
    "brand": "GENUS",
    "product": "Compact Bleaching Powder",
    "text": "Smells absolutely luxurious and keeps my hair fresh despite the sweat and dust. Fully addressed dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing. 10/10 salon-grade quality.",
    "stars": 5
  },
  {
    "id": 72,
    "name": "Buraq Rehman",
    "initials": "BR",
    "city": "Abbottabad",
    "pureCity": "Abbottabad",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "The Reconstructing Mask has completely transformed my hair. I was struggling with split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 4
  },
  {
    "id": 73,
    "name": "Maya Javed",
    "initials": "MJ",
    "city": "Hyderabad",
    "pureCity": "Hyderabad",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "The Reconstructing Mask has completely transformed my hair. I was struggling with Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 74,
    "name": "Fatima Iqbal",
    "initials": "FI",
    "city": "I-8/1, Islamabad",
    "pureCity": "Islamabad",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 75,
    "name": "Iqra Iqbal",
    "initials": "II",
    "city": "Gujranwala",
    "pureCity": "Gujranwala",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes. This product restored the natural texture and shine beautifully.",
    "stars": 5
  },
  {
    "id": 76,
    "name": "Mawra Zafar",
    "initials": "MZ",
    "city": "Hyderabad",
    "pureCity": "Hyderabad",
    "brand": "UNA",
    "product": "UNA Compensator Shampoo",
    "text": "Honestly, I was skeptical because of the hard water, but the UNA Compensator Shampoo is a miracle worker. Saved me from heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 77,
    "name": "Hira Lodi",
    "initials": "HL",
    "city": "Sargodha",
    "pureCity": "Sargodha",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "The Oxygen Activator Cream has completely transformed my hair. I was struggling with the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 78,
    "name": "Mustafa Qureshi",
    "initials": "MQ",
    "city": "PECHS, Karachi",
    "pureCity": "Karachi",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Shampoo",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 79,
    "name": "Yasir Sharif",
    "initials": "YS",
    "city": "Abbottabad",
    "pureCity": "Abbottabad",
    "brand": "GENUS",
    "product": "Compact Bleaching Powder",
    "text": "Hands down the best treatment for color-treated hair. The Compact Bleaching Powder healed my hair from severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes, and made the color look so rich and vibrant.",
    "stars": 5
  },
  {
    "id": 80,
    "name": "Aiman Raza",
    "initials": "AR",
    "city": "Sargodha",
    "pureCity": "Sargodha",
    "brand": "GENUS",
    "product": "Compact Bleaching Powder",
    "text": "Hands down the best treatment for color-treated hair. The Compact Bleaching Powder healed my hair from split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly, and made the color look so rich and vibrant.",
    "stars": 4
  },
  {
    "id": 81,
    "name": "Yumna Javed",
    "initials": "YJ",
    "city": "Abbottabad",
    "pureCity": "Abbottabad",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 82,
    "name": "Fahad Iqbal",
    "initials": "FI",
    "city": "Hyderabad",
    "pureCity": "Hyderabad",
    "brand": "UNA",
    "product": "UNA Compensator Shampoo",
    "text": "The UNA Compensator Shampoo has completely transformed my hair. I was struggling with dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 83,
    "name": "Sadia Mirza",
    "initials": "SM",
    "city": "Rawalpindi",
    "pureCity": "Rawalpindi",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Smells absolutely luxurious and keeps my hair fresh despite the sweat and dust. Fully addressed stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes. 10/10 salon-grade quality.",
    "stars": 5
  },
  {
    "id": 84,
    "name": "Komal Khan",
    "initials": "KK",
    "city": "Sialkot",
    "pureCity": "Sialkot",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "Honestly, I was skeptical because of the hard water, but the Harmonic Color is a miracle worker. Saved me from the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 85,
    "name": "Shahrukh Javed",
    "initials": "SJ",
    "city": "Bahawalpur",
    "pureCity": "Bahawalpur",
    "brand": "GENUS",
    "product": "Compact Bleaching Powder",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed split ends and rough textures. The Mediterranean Oil smells heavenly, like fresh Tuscan oranges, and absorbs instantly, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 86,
    "name": "Mahira Javed",
    "initials": "MJ",
    "city": "Peshawar",
    "pureCity": "Peshawar",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "Smells absolutely luxurious and keeps my hair fresh despite the sweat and dust. Fully addressed stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes. 10/10 salon-grade quality.",
    "stars": 5
  },
  {
    "id": 87,
    "name": "Zoya Abbasi",
    "initials": "ZA",
    "city": "Sialkot",
    "pureCity": "Sialkot",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Very premium product. You only need a tiny drop and it lathers beautifully. Fixed dandruff and itchy scalp in the sweltering heat. The UNA scalp treatment feels so cooling and soothing, and feels extremely nourishing. Worth every Rupee!",
    "stars": 5
  },
  {
    "id": 88,
    "name": "Sajal Javed",
    "initials": "SJ",
    "city": "Karachi",
    "pureCity": "Karachi",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "Using UNA's range for 3 weeks now. My stylist in Karachi suggested it to fix the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again. The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  },
  {
    "id": 89,
    "name": "Areesha Rehman",
    "initials": "AR",
    "city": "Bahawalpur",
    "pureCity": "Bahawalpur",
    "brand": "GENUS",
    "product": "GENUS Clarifying Shampoo",
    "text": "Best professional hair care available in Pakistan! Imported directly from Italy and the quality shows. It rescued my hair from stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes. Highly recommended!",
    "stars": 5
  },
  {
    "id": 90,
    "name": "Rabia Qureshi",
    "initials": "RQ",
    "city": "F-10 Markaz, Islamabad",
    "pureCity": "Islamabad",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "The Mediterranean Oil has completely transformed my hair. I was struggling with stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 91,
    "name": "Saba Sharif",
    "initials": "SS",
    "city": "Abbottabad",
    "pureCity": "Abbottabad",
    "brand": "GENUS",
    "product": "Compact Bleaching Powder",
    "text": "The Compact Bleaching Powder has completely transformed my hair. I was struggling with the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 4
  },
  {
    "id": 92,
    "name": "Areesha Mirza",
    "initials": "AM",
    "city": "Quetta",
    "pureCity": "Quetta",
    "brand": "UNA",
    "product": "UNA Hair Treatment",
    "text": "The UNA Hair Treatment has completely transformed my hair. I was struggling with severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 93,
    "name": "Bilal Siddiqui",
    "initials": "BS",
    "city": "Peshawar",
    "pureCity": "Peshawar",
    "brand": "GENUS",
    "product": "Compact Bleaching Powder",
    "text": "The Compact Bleaching Powder has completely transformed my hair. I was struggling with the salty hard water in Karachi DHA which ruined my hair. Since using this, my hair feels soft and healthy again, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 94,
    "name": "Maheen Shah",
    "initials": "MS",
    "city": "Karachi",
    "pureCity": "Karachi",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "Honestly, I was skeptical because of the hard water, but the Reconstructing Mask is a miracle worker. Saved me from heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated. Will definitely buy again!",
    "stars": 4
  },
  {
    "id": 95,
    "name": "Asad Dar",
    "initials": "AD",
    "city": "Faisalabad",
    "pureCity": "Faisalabad",
    "brand": "GENUS",
    "product": "GENUS Clarifying Shampoo",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to heat damage from straightening for the wedding season. It keeps my strands completely protected and hydrated. This product restored the natural texture and shine beautifully.",
    "stars": 4
  },
  {
    "id": 96,
    "name": "Aiman Abbasi",
    "initials": "AA",
    "city": "Karachi",
    "pureCity": "Karachi",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "Absolute lifesaver for wedding season! Constant blow-drying and styling led to dullness and roughness. It adds this amazing, mirror-like Italian salon shine without weighing down my hair. This product restored the natural texture and shine beautifully.",
    "stars": 5
  },
  {
    "id": 97,
    "name": "Nida Butt",
    "initials": "NB",
    "city": "Sialkot",
    "pureCity": "Sialkot",
    "brand": "MAXY LOOK",
    "product": "Reconstructing Mask",
    "text": "The Reconstructing Mask has completely transformed my hair. I was struggling with severe frizz and dryness from bleaching. The reconstructing mask worked wonders in just two washes, but this solved it. My strands feel incredibly silky and soft now!",
    "stars": 5
  },
  {
    "id": 98,
    "name": "Taimoor Iqbal",
    "initials": "TI",
    "city": "Quetta",
    "pureCity": "Quetta",
    "brand": "VERSUM 2.0",
    "product": "Oxygen Activator Cream",
    "text": "Honestly, I was skeptical because of the hard water, but the Oxygen Activator Cream is a miracle worker. Saved me from Lahore's intense summer humidity that always made my hair look like a nest. This completely smoothened it! Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 99,
    "name": "Eshal Siddiqui",
    "initials": "ES",
    "city": "Hyderabad",
    "pureCity": "Hyderabad",
    "brand": "VERSUM 2.0",
    "product": "Harmonic Color",
    "text": "Honestly, I was skeptical because of the hard water, but the Harmonic Color is a miracle worker. Saved me from stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes. Will definitely buy again!",
    "stars": 5
  },
  {
    "id": 100,
    "name": "Fiza Javed",
    "initials": "FJ",
    "city": "Hyderabad",
    "pureCity": "Hyderabad",
    "brand": "VERSUM 2.0",
    "product": "Mediterranean Oil",
    "text": "Using VERSUM 2.0's range for 3 weeks now. My stylist in Hyderabad suggested it to fix stubborn grey coverage. The Harmonic Color is gentle, smells amazing, and didn't dry out my scalp like local dyes. The difference is night and day \u2014 my hair has so much bounce and shine.",
    "stars": 5
  }
];
